// eslint-disable-next-line @typescript-eslint/no-var-requires
import * as pack from "../package.json" assert { type: "json" };

export const headerComment = `/**
 * GENERATED FILE: DO NOT EDIT
 * This file was generated by radix-colors-kotlin v${pack.default.version}
 * Visit: https://github.com/eklipse2k8/radix-colors-kotlin for more information.
 */
`;
