/**
 * GENERATED FILE: DO NOT EDIT
 * This file was generated by radix-colors-kotlin v1.2.0
 * Visit: https://github.com/eklipse2k8/radix-colors-kotlin for more information.
 */

package com.eklipse2k8.radixcolor

import androidx.compose.ui.graphics.Color

/** [Radix Colors] A gorgeous, accessible color system. */
object RadixColors {
    /** [Radix Colors] Collection: amber */
    @JVMStatic
    val amber =
        listOf(
              Color.hsl(39, 0.700, 0.990),
              Color.hsl(40, 1.000, 0.965),
              Color.hsl(44, 1.000, 0.917),
              Color.hsl(43, 1.000, 0.868),
              Color.hsl(42, 1.000, 0.818),
              Color.hsl(38, 0.997, 0.763),
              Color.hsl(36, 0.861, 0.671),
              Color.hsl(35, 0.852, 0.551),
              Color.hsl(39, 1.000, 0.570),
              Color.hsl(35, 1.000, 0.555),
              Color.hsl(30, 1.000, 0.340),
              Color.hsl(20, 0.800, 0.170),
        )
    /** [Radix Colors] Collection: amberA */
    @JVMStatic
    val amberA =
        listOf(
             Color.hsl(40, 0.949, 0.387, 0.016),
             Color.hsl(40, 1.000, 0.503, 0.071),
             Color.hsl(44, 1.000, 0.501, 0.165),
             Color.hsl(43, 1.000, 0.500, 0.263),
             Color.hsl(42, 1.000, 0.500, 0.365),
             Color.hsl(38, 1.000, 0.501, 0.475),
             Color.hsl(36, 0.999, 0.462, 0.612),
             Color.hsl(35, 0.998, 0.460, 0.832),
             Color.hsl(39, 1.000, 0.500, 0.859),
             Color.hsl(35, 1.000, 0.500, 0.891),
             Color.hsl(29, 1.000, 0.336, 0.980),
             Color.hsl(20, 0.998, 0.141, 0.965),
        )
    /** [Radix Colors] Collection: amberDark */
    @JVMStatic
    val amberDark =
        listOf(
              Color.hsl(36, 1.000, 0.061),
              Color.hsl(35, 1.000, 0.076),
              Color.hsl(32, 1.000, 0.102),
              Color.hsl(32, 1.000, 0.124),
              Color.hsl(33, 1.000, 0.146),
              Color.hsl(35, 1.000, 0.171),
              Color.hsl(35, 0.910, 0.216),
              Color.hsl(36, 1.000, 0.255),
              Color.hsl(39, 1.000, 0.570),
              Color.hsl(43, 1.000, 0.640),
              Color.hsl(39, 0.900, 0.498),
              Color.hsl(39, 0.970, 0.932),
        )
    /** [Radix Colors] Collection: amberDarkA */
    @JVMStatic
    val amberDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(31, 1.000, 0.497, 0.036),
             Color.hsl(27, 1.000, 0.499, 0.094),
             Color.hsl(29, 1.000, 0.500, 0.143),
             Color.hsl(31, 1.000, 0.500, 0.192),
             Color.hsl(35, 1.000, 0.500, 0.250),
             Color.hsl(34, 0.996, 0.529, 0.331),
             Color.hsl(36, 1.000, 0.500, 0.442),
             Color.hsl(40, 1.000, 0.572, 0.980),
             Color.hsl(44, 1.000, 0.642, 0.980),
             Color.hsl(39, 0.999, 0.527, 0.938),
             Color.hsl(45, 1.000, 0.942, 0.980),
        )
    /** [Radix Colors] Collection: blackA */
    @JVMStatic
    val blackA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.012),
             Color.hsl(0, 0.000, 0.000, 0.027),
             Color.hsl(0, 0.000, 0.000, 0.047),
             Color.hsl(0, 0.000, 0.000, 0.071),
             Color.hsl(0, 0.000, 0.000, 0.090),
             Color.hsl(0, 0.000, 0.000, 0.114),
             Color.hsl(0, 0.000, 0.000, 0.141),
             Color.hsl(0, 0.000, 0.000, 0.220),
             Color.hsl(0, 0.000, 0.000, 0.439),
             Color.hsl(0, 0.000, 0.000, 0.478),
             Color.hsl(0, 0.000, 0.000, 0.565),
             Color.hsl(0, 0.000, 0.000, 0.910),
        )
    /** [Radix Colors] Collection: blue */
    @JVMStatic
    val blue =
        listOf(
              Color.hsl(206, 1.000, 0.992),
              Color.hsl(210, 1.000, 0.980),
              Color.hsl(209, 1.000, 0.965),
              Color.hsl(210, 0.988, 0.940),
              Color.hsl(209, 0.950, 0.901),
              Color.hsl(209, 0.812, 0.845),
              Color.hsl(208, 0.775, 0.769),
              Color.hsl(206, 0.819, 0.653),
              Color.hsl(206, 1.000, 0.500),
              Color.hsl(208, 1.000, 0.473),
              Color.hsl(211, 1.000, 0.432),
              Color.hsl(211, 1.000, 0.150),
        )
    /** [Radix Colors] Collection: blueA */
    @JVMStatic
    val blueA =
        listOf(
             Color.hsl(210, 1.000, 0.510, 0.016),
             Color.hsl(210, 1.000, 0.510, 0.040),
             Color.hsl(210, 1.000, 0.503, 0.071),
             Color.hsl(210, 1.000, 0.501, 0.118),
             Color.hsl(208, 0.991, 0.471, 0.189),
             Color.hsl(209, 0.995, 0.453, 0.283),
             Color.hsl(208, 0.999, 0.438, 0.412),
             Color.hsl(206, 0.998, 0.451, 0.632),
             Color.hsl(206, 1.000, 0.500, 0.980),
             Color.hsl(208, 1.000, 0.472, 0.980),
             Color.hsl(212, 1.000, 0.430, 0.980),
             Color.hsl(213, 1.000, 0.144, 0.980),
        )
    /** [Radix Colors] Collection: blueDark */
    @JVMStatic
    val blueDark =
        listOf(
              Color.hsl(212, 0.350, 0.092),
              Color.hsl(216, 0.500, 0.118),
              Color.hsl(214, 0.594, 0.153),
              Color.hsl(214, 0.658, 0.179),
              Color.hsl(213, 0.712, 0.202),
              Color.hsl(212, 0.774, 0.231),
              Color.hsl(211, 0.851, 0.274),
              Color.hsl(211, 0.897, 0.341),
              Color.hsl(206, 1.000, 0.500),
              Color.hsl(209, 1.000, 0.606),
              Color.hsl(210, 1.000, 0.661),
              Color.hsl(206, 0.980, 0.958),
        )
    /** [Radix Colors] Collection: blueDarkA */
    @JVMStatic
    val blueDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(221, 0.978, 0.524, 0.059),
             Color.hsl(215, 0.993, 0.542, 0.135),
             Color.hsl(215, 0.993, 0.538, 0.198),
             Color.hsl(213, 0.994, 0.528, 0.252),
             Color.hsl(212, 0.999, 0.517, 0.323),
             Color.hsl(211, 1.000, 0.507, 0.435),
             Color.hsl(211, 0.998, 0.509, 0.597),
             Color.hsl(205, 1.000, 0.500, 0.980),
             Color.hsl(208, 1.000, 0.607, 0.980),
             Color.hsl(209, 1.000, 0.663, 0.980),
             Color.hsl(196, 1.000, 0.968, 0.980),
        )
    /** [Radix Colors] Collection: bronze */
    @JVMStatic
    val bronze =
        listOf(
              Color.hsl(15, 0.300, 0.991),
              Color.hsl(17, 0.636, 0.978),
              Color.hsl(17, 0.421, 0.952),
              Color.hsl(17, 0.352, 0.921),
              Color.hsl(17, 0.315, 0.882),
              Color.hsl(17, 0.290, 0.830),
              Color.hsl(17, 0.269, 0.756),
              Color.hsl(17, 0.251, 0.665),
              Color.hsl(17, 0.200, 0.540),
              Color.hsl(17, 0.181, 0.501),
              Color.hsl(15, 0.200, 0.431),
              Color.hsl(12, 0.220, 0.215),
        )
    /** [Radix Colors] Collection: bronzeA */
    @JVMStatic
    val bronzeA =
        listOf(
             Color.hsl(0, 0.893, 0.183, 0.012),
             Color.hsl(17, 0.951, 0.401, 0.036),
             Color.hsl(18, 0.983, 0.298, 0.067),
             Color.hsl(17, 0.996, 0.260, 0.106),
             Color.hsl(19, 0.996, 0.238, 0.157),
             Color.hsl(17, 0.992, 0.225, 0.220),
             Color.hsl(18, 0.997, 0.216, 0.310),
             Color.hsl(17, 0.995, 0.202, 0.420),
             Color.hsl(18, 0.999, 0.167, 0.553),
             Color.hsl(17, 0.992, 0.154, 0.589),
             Color.hsl(15, 0.999, 0.132, 0.655),
             Color.hsl(12, 0.987, 0.057, 0.832),
        )
    /** [Radix Colors] Collection: bronzeDark */
    @JVMStatic
    val bronzeDark =
        listOf(
              Color.hsl(17, 0.100, 0.088),
              Color.hsl(15, 0.148, 0.106),
              Color.hsl(15, 0.163, 0.143),
              Color.hsl(16, 0.171, 0.172),
              Color.hsl(16, 0.176, 0.196),
              Color.hsl(16, 0.181, 0.229),
              Color.hsl(17, 0.188, 0.288),
              Color.hsl(17, 0.196, 0.380),
              Color.hsl(17, 0.200, 0.540),
              Color.hsl(18, 0.240, 0.590),
              Color.hsl(18, 0.350, 0.685),
              Color.hsl(18, 0.570, 0.941),
        )
    /** [Radix Colors] Collection: bronzeDarkA */
    @JVMStatic
    val bronzeDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(20, 0.882, 0.742, 0.027),
             Color.hsl(10, 0.994, 0.830, 0.074),
             Color.hsl(18, 0.960, 0.811, 0.114),
             Color.hsl(18, 0.994, 0.817, 0.148),
             Color.hsl(15, 0.981, 0.824, 0.192),
             Color.hsl(16, 0.992, 0.829, 0.270),
             Color.hsl(18, 0.995, 0.826, 0.396),
             Color.hsl(18, 0.993, 0.850, 0.592),
             Color.hsl(18, 0.996, 0.852, 0.657),
             Color.hsl(17, 0.999, 0.861, 0.774),
             Color.hsl(20, 0.998, 0.964, 0.974),
        )
    /** [Radix Colors] Collection: brown */
    @JVMStatic
    val brown =
        listOf(
              Color.hsl(30, 0.400, 0.991),
              Color.hsl(30, 0.500, 0.976),
              Color.hsl(30, 0.525, 0.946),
              Color.hsl(30, 0.530, 0.912),
              Color.hsl(29, 0.529, 0.868),
              Color.hsl(29, 0.525, 0.809),
              Color.hsl(29, 0.515, 0.728),
              Color.hsl(28, 0.500, 0.631),
              Color.hsl(28, 0.340, 0.510),
              Color.hsl(27, 0.318, 0.476),
              Color.hsl(25, 0.300, 0.410),
              Color.hsl(20, 0.300, 0.190),
        )
    /** [Radix Colors] Collection: brownA */
    @JVMStatic
    val brownA =
        listOf(
             Color.hsl(30, 0.943, 0.346, 0.012),
             Color.hsl(30, 0.943, 0.346, 0.036),
             Color.hsl(30, 0.977, 0.339, 0.083),
             Color.hsl(31, 0.985, 0.342, 0.134),
             Color.hsl(29, 1.000, 0.343, 0.200),
             Color.hsl(28, 0.992, 0.346, 0.291),
             Color.hsl(29, 0.998, 0.338, 0.412),
             Color.hsl(28, 1.000, 0.333, 0.553),
             Color.hsl(28, 0.999, 0.255, 0.655),
             Color.hsl(27, 0.997, 0.224, 0.675),
             Color.hsl(25, 0.998, 0.173, 0.714),
             Color.hsl(21, 0.994, 0.066, 0.867),
        )
    /** [Radix Colors] Collection: brownDark */
    @JVMStatic
    val brownDark =
        listOf(
              Color.hsl(22, 0.150, 0.087),
              Color.hsl(20, 0.283, 0.104),
              Color.hsl(20, 0.280, 0.140),
              Color.hsl(21, 0.284, 0.165),
              Color.hsl(22, 0.287, 0.189),
              Color.hsl(23, 0.290, 0.223),
              Color.hsl(25, 0.295, 0.278),
              Color.hsl(27, 0.301, 0.359),
              Color.hsl(28, 0.340, 0.510),
              Color.hsl(28, 0.414, 0.558),
              Color.hsl(28, 0.600, 0.645),
              Color.hsl(30, 0.670, 0.940),
        )
    /** [Radix Colors] Collection: brownDarkA */
    @JVMStatic
    val brownDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(22, 0.996, 0.536, 0.035),
             Color.hsl(18, 0.978, 0.690, 0.088),
             Color.hsl(21, 0.982, 0.710, 0.123),
             Color.hsl(25, 0.984, 0.721, 0.158),
             Color.hsl(25, 0.987, 0.735, 0.206),
             Color.hsl(25, 0.990, 0.746, 0.289),
             Color.hsl(28, 0.992, 0.753, 0.407),
             Color.hsl(28, 1.000, 0.748, 0.642),
             Color.hsl(28, 0.999, 0.749, 0.712),
             Color.hsl(28, 0.999, 0.749, 0.843),
             Color.hsl(32, 0.982, 0.957, 0.979),
        )
    /** [Radix Colors] Collection: crimson */
    @JVMStatic
    val crimson =
        listOf(
              Color.hsl(332, 1.000, 0.994),
              Color.hsl(330, 1.000, 0.984),
              Color.hsl(331, 0.856, 0.966),
              Color.hsl(331, 0.781, 0.942),
              Color.hsl(332, 0.721, 0.911),
              Color.hsl(333, 0.670, 0.867),
              Color.hsl(335, 0.635, 0.804),
              Color.hsl(336, 0.623, 0.729),
              Color.hsl(336, 0.800, 0.578),
              Color.hsl(336, 0.737, 0.535),
              Color.hsl(336, 0.750, 0.472),
              Color.hsl(340, 0.650, 0.145),
        )
    /** [Radix Colors] Collection: crimsonA */
    @JVMStatic
    val crimsonA =
        listOf(
             Color.hsl(340, 1.000, 0.510, 0.012),
             Color.hsl(330, 1.000, 0.510, 0.032),
             Color.hsl(332, 0.991, 0.471, 0.063),
             Color.hsl(331, 0.999, 0.443, 0.102),
             Color.hsl(333, 0.999, 0.423, 0.153),
             Color.hsl(333, 0.995, 0.405, 0.224),
             Color.hsl(335, 0.997, 0.391, 0.322),
             Color.hsl(336, 0.995, 0.385, 0.440),
             Color.hsl(336, 0.999, 0.443, 0.761),
             Color.hsl(336, 1.000, 0.425, 0.808),
             Color.hsl(336, 0.998, 0.403, 0.883),
             Color.hsl(340, 0.990, 0.100, 0.950),
        )
    /** [Radix Colors] Collection: crimsonDark */
    @JVMStatic
    val crimsonDark =
        listOf(
              Color.hsl(335, 0.200, 0.096),
              Color.hsl(335, 0.322, 0.116),
              Color.hsl(335, 0.425, 0.165),
              Color.hsl(335, 0.472, 0.193),
              Color.hsl(335, 0.509, 0.218),
              Color.hsl(335, 0.557, 0.253),
              Color.hsl(336, 0.629, 0.308),
              Color.hsl(336, 0.749, 0.390),
              Color.hsl(336, 0.800, 0.578),
              Color.hsl(339, 0.841, 0.626),
              Color.hsl(341, 0.900, 0.673),
              Color.hsl(332, 0.870, 0.960),
        )
    /** [Radix Colors] Collection: crimsonDarkA */
    @JVMStatic
    val crimsonDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(336, 0.968, 0.532, 0.045),
             Color.hsl(335, 0.987, 0.593, 0.138),
             Color.hsl(336, 0.991, 0.599, 0.191),
             Color.hsl(335, 0.994, 0.594, 0.244),
             Color.hsl(335, 0.994, 0.594, 0.315),
             Color.hsl(336, 0.995, 0.578, 0.439),
             Color.hsl(336, 0.999, 0.554, 0.642),
             Color.hsl(336, 0.999, 0.628, 0.903),
             Color.hsl(339, 0.999, 0.663, 0.934),
             Color.hsl(341, 0.999, 0.695, 0.965),
             Color.hsl(327, 1.000, 0.971, 0.980),
        )
    /** [Radix Colors] Collection: cyan */
    @JVMStatic
    val cyan =
        listOf(
              Color.hsl(185, 0.600, 0.987),
              Color.hsl(185, 0.733, 0.971),
              Color.hsl(186, 0.702, 0.944),
              Color.hsl(186, 0.638, 0.906),
              Color.hsl(187, 0.583, 0.854),
              Color.hsl(188, 0.546, 0.784),
              Color.hsl(189, 0.537, 0.687),
              Color.hsl(189, 0.603, 0.525),
              Color.hsl(190, 0.950, 0.390),
              Color.hsl(191, 0.912, 0.368),
              Color.hsl(192, 0.850, 0.310),
              Color.hsl(192, 0.880, 0.125),
        )
    /** [Radix Colors] Collection: cyanA */
    @JVMStatic
    val cyanA =
        listOf(
             Color.hsl(195, 0.952, 0.412, 0.020),
             Color.hsl(185, 0.999, 0.423, 0.051),
             Color.hsl(186, 0.978, 0.422, 0.095),
             Color.hsl(186, 0.999, 0.385, 0.153),
             Color.hsl(187, 0.993, 0.366, 0.232),
             Color.hsl(188, 0.994, 0.354, 0.334),
             Color.hsl(189, 0.996, 0.350, 0.483),
             Color.hsl(189, 0.999, 0.376, 0.761),
             Color.hsl(190, 1.000, 0.378, 0.980),
             Color.hsl(191, 0.999, 0.346, 0.969),
             Color.hsl(192, 1.000, 0.276, 0.953),
             Color.hsl(192, 1.000, 0.110, 0.980),
        )
    /** [Radix Colors] Collection: cyanDark */
    @JVMStatic
    val cyanDark =
        listOf(
              Color.hsl(192, 0.600, 0.072),
              Color.hsl(192, 0.714, 0.082),
              Color.hsl(192, 0.759, 0.108),
              Color.hsl(192, 0.793, 0.128),
              Color.hsl(192, 0.825, 0.146),
              Color.hsl(192, 0.866, 0.169),
              Color.hsl(192, 0.926, 0.201),
              Color.hsl(192, 1.000, 0.245),
              Color.hsl(190, 0.950, 0.390),
              Color.hsl(188, 1.000, 0.400),
              Color.hsl(186, 1.000, 0.422),
              Color.hsl(185, 0.730, 0.932),
        )
    /** [Radix Colors] Collection: cyanDarkA */
    @JVMStatic
    val cyanDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(196, 1.000, 0.500, 0.031),
             Color.hsl(192, 0.980, 0.509, 0.085),
             Color.hsl(194, 0.996, 0.513, 0.133),
             Color.hsl(192, 0.995, 0.513, 0.173),
             Color.hsl(193, 0.997, 0.504, 0.226),
             Color.hsl(192, 1.000, 0.500, 0.310),
             Color.hsl(193, 1.000, 0.500, 0.425),
             Color.hsl(190, 0.998, 0.508, 0.731),
             Color.hsl(188, 1.000, 0.500, 0.775),
             Color.hsl(186, 1.000, 0.499, 0.824),
             Color.hsl(185, 0.998, 0.951, 0.978),
        )
    /** [Radix Colors] Collection: gold */
    @JVMStatic
    val gold =
        listOf(
              Color.hsl(50, 0.200, 0.991),
              Color.hsl(47, 0.529, 0.967),
              Color.hsl(46, 0.382, 0.937),
              Color.hsl(44, 0.327, 0.901),
              Color.hsl(43, 0.299, 0.857),
              Color.hsl(41, 0.283, 0.798),
              Color.hsl(39, 0.276, 0.719),
              Color.hsl(36, 0.272, 0.618),
              Color.hsl(36, 0.200, 0.495),
              Color.hsl(36, 0.198, 0.457),
              Color.hsl(36, 0.200, 0.390),
              Color.hsl(36, 0.160, 0.200),
        )
    /** [Radix Colors] Collection: goldA */
    @JVMStatic
    val goldA =
        listOf(
             Color.hsl(60, 0.893, 0.183, 0.012),
             Color.hsl(47, 0.999, 0.346, 0.051),
             Color.hsl(45, 0.970, 0.279, 0.087),
             Color.hsl(46, 0.980, 0.254, 0.134),
             Color.hsl(43, 0.984, 0.226, 0.185),
             Color.hsl(41, 0.997, 0.220, 0.259),
             Color.hsl(38, 0.998, 0.215, 0.357),
             Color.hsl(36, 0.993, 0.215, 0.487),
             Color.hsl(36, 0.999, 0.162, 0.604),
             Color.hsl(36, 0.992, 0.146, 0.636),
             Color.hsl(35, 0.991, 0.112, 0.687),
             Color.hsl(38, 0.980, 0.038, 0.832),
        )
    /** [Radix Colors] Collection: goldDark */
    @JVMStatic
    val goldDark =
        listOf(
              Color.hsl(44, 0.090, 0.083),
              Color.hsl(43, 0.143, 0.096),
              Color.hsl(42, 0.155, 0.130),
              Color.hsl(41, 0.164, 0.156),
              Color.hsl(41, 0.169, 0.178),
              Color.hsl(40, 0.176, 0.208),
              Color.hsl(38, 0.185, 0.264),
              Color.hsl(36, 0.196, 0.351),
              Color.hsl(36, 0.200, 0.495),
              Color.hsl(36, 0.223, 0.545),
              Color.hsl(35, 0.300, 0.640),
              Color.hsl(49, 0.520, 0.938),
        )
    /** [Radix Colors] Collection: goldDarkA */
    @JVMStatic
    val goldDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(40, 0.937, 0.706, 0.022),
             Color.hsl(40, 0.975, 0.806, 0.065),
             Color.hsl(40, 0.959, 0.808, 0.100),
             Color.hsl(38, 0.973, 0.821, 0.130),
             Color.hsl(39, 0.972, 0.825, 0.169),
             Color.hsl(37, 0.993, 0.824, 0.246),
             Color.hsl(35, 0.987, 0.822, 0.363),
             Color.hsl(36, 0.997, 0.828, 0.552),
             Color.hsl(35, 0.992, 0.837, 0.613),
             Color.hsl(35, 0.993, 0.853, 0.725),
             Color.hsl(49, 0.986, 0.967, 0.966),
        )
    /** [Radix Colors] Collection: grass */
    @JVMStatic
    val grass =
        listOf(
              Color.hsl(116, 0.500, 0.989),
              Color.hsl(120, 0.600, 0.971),
              Color.hsl(120, 0.536, 0.948),
              Color.hsl(121, 0.475, 0.914),
              Color.hsl(122, 0.426, 0.865),
              Color.hsl(124, 0.390, 0.797),
              Color.hsl(126, 0.371, 0.702),
              Color.hsl(131, 0.381, 0.563),
              Color.hsl(131, 0.410, 0.465),
              Color.hsl(132, 0.431, 0.422),
              Color.hsl(133, 0.500, 0.325),
              Color.hsl(130, 0.300, 0.149),
        )
    /** [Radix Colors] Collection: grassA */
    @JVMStatic
    val grassA =
        listOf(
             Color.hsl(120, 0.949, 0.387, 0.016),
             Color.hsl(120, 0.949, 0.387, 0.048),
             Color.hsl(120, 0.980, 0.355, 0.079),
             Color.hsl(120, 0.987, 0.315, 0.126),
             Color.hsl(122, 0.985, 0.299, 0.193),
             Color.hsl(125, 0.992, 0.279, 0.283),
             Color.hsl(125, 0.999, 0.270, 0.408),
             Color.hsl(131, 1.000, 0.276, 0.604),
             Color.hsl(131, 0.997, 0.263, 0.726),
             Color.hsl(132, 0.999, 0.240, 0.761),
             Color.hsl(133, 0.995, 0.195, 0.840),
             Color.hsl(128, 0.980, 0.049, 0.895),
        )
    /** [Radix Colors] Collection: grassDark */
    @JVMStatic
    val grassDark =
        listOf(
              Color.hsl(146, 0.300, 0.074),
              Color.hsl(136, 0.333, 0.088),
              Color.hsl(137, 0.360, 0.114),
              Color.hsl(137, 0.376, 0.137),
              Color.hsl(136, 0.387, 0.160),
              Color.hsl(135, 0.396, 0.191),
              Color.hsl(134, 0.403, 0.238),
              Color.hsl(131, 0.401, 0.308),
              Color.hsl(131, 0.410, 0.465),
              Color.hsl(131, 0.390, 0.521),
              Color.hsl(131, 0.430, 0.572),
              Color.hsl(137, 0.720, 0.940),
        )
    /** [Radix Colors] Collection: grassDarkA */
    @JVMStatic
    val grassDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(107, 0.972, 0.619, 0.022),
             Color.hsl(128, 0.965, 0.698, 0.066),
             Color.hsl(130, 1.000, 0.702, 0.100),
             Color.hsl(130, 0.982, 0.691, 0.140),
             Color.hsl(132, 0.999, 0.693, 0.187),
             Color.hsl(132, 0.999, 0.698, 0.261),
             Color.hsl(130, 0.996, 0.705, 0.370),
             Color.hsl(130, 0.997, 0.706, 0.618),
             Color.hsl(131, 1.000, 0.735, 0.674),
             Color.hsl(130, 0.997, 0.756, 0.731),
             Color.hsl(137, 1.000, 0.958, 0.980),
        )
    /** [Radix Colors] Collection: gray */
    @JVMStatic
    val gray =
        listOf(
              Color.hsl(0, 0.000, 0.990),
              Color.hsl(0, 0.000, 0.973),
              Color.hsl(0, 0.000, 0.951),
              Color.hsl(0, 0.000, 0.930),
              Color.hsl(0, 0.000, 0.909),
              Color.hsl(0, 0.000, 0.887),
              Color.hsl(0, 0.000, 0.858),
              Color.hsl(0, 0.000, 0.780),
              Color.hsl(0, 0.000, 0.561),
              Color.hsl(0, 0.000, 0.523),
              Color.hsl(0, 0.000, 0.435),
              Color.hsl(0, 0.000, 0.090),
        )
    /** [Radix Colors] Collection: grayA */
    @JVMStatic
    val grayA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.012),
             Color.hsl(0, 0.000, 0.000, 0.027),
             Color.hsl(0, 0.000, 0.000, 0.047),
             Color.hsl(0, 0.000, 0.000, 0.071),
             Color.hsl(0, 0.000, 0.000, 0.090),
             Color.hsl(0, 0.000, 0.000, 0.114),
             Color.hsl(0, 0.000, 0.000, 0.141),
             Color.hsl(0, 0.000, 0.000, 0.220),
             Color.hsl(0, 0.000, 0.000, 0.439),
             Color.hsl(0, 0.000, 0.000, 0.478),
             Color.hsl(0, 0.000, 0.000, 0.565),
             Color.hsl(0, 0.000, 0.000, 0.910),
        )
    /** [Radix Colors] Collection: grayDark */
    @JVMStatic
    val grayDark =
        listOf(
              Color.hsl(0, 0.000, 0.085),
              Color.hsl(0, 0.000, 0.110),
              Color.hsl(0, 0.000, 0.136),
              Color.hsl(0, 0.000, 0.158),
              Color.hsl(0, 0.000, 0.179),
              Color.hsl(0, 0.000, 0.205),
              Color.hsl(0, 0.000, 0.243),
              Color.hsl(0, 0.000, 0.312),
              Color.hsl(0, 0.000, 0.439),
              Color.hsl(0, 0.000, 0.494),
              Color.hsl(0, 0.000, 0.628),
              Color.hsl(0, 0.000, 0.930),
        )
    /** [Radix Colors] Collection: grayDarkA */
    @JVMStatic
    val grayDarkA =
        listOf(
             Color.hsl(0, 0.000, 1.000, 0.000),
             Color.hsl(0, 0.000, 1.000, 0.026),
             Color.hsl(0, 0.000, 1.000, 0.056),
             Color.hsl(0, 0.000, 1.000, 0.077),
             Color.hsl(0, 0.000, 1.000, 0.103),
             Color.hsl(0, 0.000, 1.000, 0.129),
             Color.hsl(0, 0.000, 1.000, 0.172),
             Color.hsl(0, 0.000, 1.000, 0.249),
             Color.hsl(0, 0.000, 1.000, 0.386),
             Color.hsl(0, 0.000, 1.000, 0.446),
             Color.hsl(0, 0.000, 1.000, 0.592),
             Color.hsl(0, 0.000, 1.000, 0.923),
        )
    /** [Radix Colors] Collection: green */
    @JVMStatic
    val green =
        listOf(
              Color.hsl(136, 0.500, 0.989),
              Color.hsl(138, 0.625, 0.969),
              Color.hsl(139, 0.552, 0.945),
              Color.hsl(140, 0.487, 0.910),
              Color.hsl(141, 0.437, 0.860),
              Color.hsl(143, 0.403, 0.790),
              Color.hsl(146, 0.385, 0.690),
              Color.hsl(151, 0.402, 0.541),
              Color.hsl(151, 0.550, 0.415),
              Color.hsl(152, 0.575, 0.376),
              Color.hsl(153, 0.670, 0.285),
              Color.hsl(155, 0.400, 0.140),
        )
    /** [Radix Colors] Collection: greenA */
    @JVMStatic
    val greenA =
        listOf(
             Color.hsl(140, 0.949, 0.387, 0.016),
             Color.hsl(138, 0.999, 0.385, 0.051),
             Color.hsl(139, 0.977, 0.369, 0.087),
             Color.hsl(139, 0.985, 0.327, 0.134),
             Color.hsl(141, 1.000, 0.304, 0.200),
             Color.hsl(142, 0.990, 0.289, 0.295),
             Color.hsl(146, 0.995, 0.276, 0.428),
             Color.hsl(151, 0.995, 0.288, 0.644),
             Color.hsl(151, 0.999, 0.280, 0.812),
             Color.hsl(152, 0.996, 0.258, 0.840),
             Color.hsl(153, 0.999, 0.210, 0.906),
             Color.hsl(155, 0.994, 0.062, 0.918),
        )
    /** [Radix Colors] Collection: greenDark */
    @JVMStatic
    val greenDark =
        listOf(
              Color.hsl(146, 0.300, 0.074),
              Color.hsl(155, 0.442, 0.084),
              Color.hsl(155, 0.467, 0.109),
              Color.hsl(154, 0.484, 0.129),
              Color.hsl(154, 0.497, 0.149),
              Color.hsl(154, 0.509, 0.176),
              Color.hsl(153, 0.518, 0.218),
              Color.hsl(151, 0.517, 0.284),
              Color.hsl(151, 0.550, 0.415),
              Color.hsl(151, 0.493, 0.465),
              Color.hsl(151, 0.500, 0.532),
              Color.hsl(137, 0.720, 0.940),
        )
    /** [Radix Colors] Collection: greenDarkA */
    @JVMStatic
    val greenDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(169, 1.000, 0.485, 0.027),
             Color.hsl(162, 0.987, 0.579, 0.070),
             Color.hsl(158, 0.986, 0.597, 0.105),
             Color.hsl(158, 0.986, 0.607, 0.140),
             Color.hsl(156, 0.999, 0.620, 0.187),
             Color.hsl(154, 0.995, 0.631, 0.257),
             Color.hsl(152, 0.997, 0.642, 0.370),
             Color.hsl(151, 0.997, 0.638, 0.605),
             Color.hsl(152, 0.999, 0.665, 0.661),
             Color.hsl(151, 0.997, 0.692, 0.740),
             Color.hsl(137, 1.000, 0.958, 0.980),
        )
    /** [Radix Colors] Collection: indigo */
    @JVMStatic
    val indigo =
        listOf(
              Color.hsl(225, 0.600, 0.994),
              Color.hsl(223, 1.000, 0.986),
              Color.hsl(223, 0.984, 0.971),
              Color.hsl(223, 0.929, 0.950),
              Color.hsl(224, 0.871, 0.920),
              Color.hsl(224, 0.819, 0.878),
              Color.hsl(225, 0.774, 0.821),
              Color.hsl(226, 0.754, 0.745),
              Color.hsl(226, 0.700, 0.555),
              Color.hsl(226, 0.586, 0.513),
              Color.hsl(226, 0.550, 0.450),
              Color.hsl(226, 0.620, 0.170),
        )
    /** [Radix Colors] Collection: indigoA */
    @JVMStatic
    val indigoA =
        listOf(
             Color.hsl(240, 0.926, 0.265, 0.008),
             Color.hsl(223, 1.000, 0.510, 0.028),
             Color.hsl(224, 1.000, 0.501, 0.059),
             Color.hsl(223, 0.980, 0.485, 0.099),
             Color.hsl(225, 0.986, 0.464, 0.150),
             Color.hsl(224, 0.995, 0.449, 0.224),
             Color.hsl(225, 0.997, 0.439, 0.318),
             Color.hsl(226, 0.995, 0.431, 0.448),
             Color.hsl(226, 1.000, 0.412, 0.757),
             Color.hsl(226, 0.998, 0.371, 0.773),
             Color.hsl(226, 0.996, 0.311, 0.797),
             Color.hsl(226, 0.993, 0.114, 0.938),
        )
    /** [Radix Colors] Collection: indigoDark */
    @JVMStatic
    val indigoDark =
        listOf(
              Color.hsl(229, 0.240, 0.100),
              Color.hsl(230, 0.364, 0.129),
              Color.hsl(228, 0.433, 0.175),
              Color.hsl(227, 0.472, 0.210),
              Color.hsl(227, 0.500, 0.241),
              Color.hsl(226, 0.529, 0.282),
              Color.hsl(226, 0.560, 0.345),
              Color.hsl(226, 0.582, 0.441),
              Color.hsl(226, 0.700, 0.555),
              Color.hsl(227, 0.752, 0.616),
              Color.hsl(228, 1.000, 0.759),
              Color.hsl(226, 0.830, 0.963),
        )
    /** [Radix Colors] Collection: indigoDarkA */
    @JVMStatic
    val indigoDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(234, 0.974, 0.599, 0.059),
             Color.hsl(228, 0.992, 0.617, 0.144),
             Color.hsl(227, 0.997, 0.620, 0.211),
             Color.hsl(227, 0.992, 0.623, 0.270),
             Color.hsl(226, 0.999, 0.621, 0.350),
             Color.hsl(226, 0.999, 0.620, 0.471),
             Color.hsl(226, 0.999, 0.621, 0.655),
             Color.hsl(226, 0.999, 0.636, 0.848),
             Color.hsl(227, 0.998, 0.677, 0.893),
             Color.hsl(227, 1.000, 0.763, 0.980),
             Color.hsl(226, 1.000, 0.975, 0.980),
        )
    /** [Radix Colors] Collection: lime */
    @JVMStatic
    val lime =
        listOf(
              Color.hsl(85, 0.500, 0.987),
              Color.hsl(85, 0.667, 0.965),
              Color.hsl(85, 0.760, 0.923),
              Color.hsl(84, 0.753, 0.875),
              Color.hsl(84, 0.715, 0.819),
              Color.hsl(82, 0.650, 0.746),
              Color.hsl(79, 0.532, 0.618),
              Color.hsl(76, 0.617, 0.451),
              Color.hsl(81, 0.670, 0.500),
              Color.hsl(80, 0.683, 0.469),
              Color.hsl(75, 0.800, 0.260),
              Color.hsl(78, 0.700, 0.115),
        )
    /** [Radix Colors] Collection: limeA */
    @JVMStatic
    val limeA =
        listOf(
             Color.hsl(80, 0.938, 0.314, 0.020),
             Color.hsl(85, 0.993, 0.402, 0.059),
             Color.hsl(84, 0.987, 0.432, 0.138),
             Color.hsl(84, 0.996, 0.430, 0.220),
             Color.hsl(85, 0.998, 0.418, 0.310),
             Color.hsl(82, 0.998, 0.393, 0.420),
             Color.hsl(79, 0.997, 0.346, 0.585),
             Color.hsl(76, 0.998, 0.337, 0.828),
             Color.hsl(81, 0.998, 0.402, 0.836),
             Color.hsl(80, 1.000, 0.376, 0.851),
             Color.hsl(75, 0.995, 0.220, 0.950),
             Color.hsl(78, 0.996, 0.084, 0.965),
        )
    /** [Radix Colors] Collection: limeDark */
    @JVMStatic
    val limeDark =
        listOf(
              Color.hsl(75, 0.550, 0.060),
              Color.hsl(74, 0.568, 0.073),
              Color.hsl(78, 0.502, 0.099),
              Color.hsl(79, 0.503, 0.121),
              Color.hsl(79, 0.526, 0.142),
              Color.hsl(78, 0.557, 0.167),
              Color.hsl(77, 0.597, 0.201),
              Color.hsl(75, 0.648, 0.245),
              Color.hsl(81, 0.670, 0.500),
              Color.hsl(75, 0.850, 0.600),
              Color.hsl(81, 0.700, 0.438),
              Color.hsl(84, 0.790, 0.926),
        )
    /** [Radix Colors] Collection: limeDarkA */
    @JVMStatic
    val limeDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(75, 0.964, 0.596, 0.022),
             Color.hsl(88, 0.980, 0.704, 0.061),
             Color.hsl(81, 0.978, 0.674, 0.096),
             Color.hsl(82, 0.984, 0.656, 0.135),
             Color.hsl(79, 0.997, 0.643, 0.182),
             Color.hsl(77, 0.991, 0.621, 0.252),
             Color.hsl(75, 1.000, 0.600, 0.342),
             Color.hsl(81, 0.998, 0.597, 0.819),
             Color.hsl(75, 0.998, 0.637, 0.936),
             Color.hsl(81, 0.999, 0.587, 0.719),
             Color.hsl(83, 1.000, 0.942, 0.980),
        )
    /** [Radix Colors] Collection: mauve */
    @JVMStatic
    val mauve =
        listOf(
              Color.hsl(300, 0.200, 0.990),
              Color.hsl(300, 0.077, 0.975),
              Color.hsl(294, 0.055, 0.953),
              Color.hsl(289, 0.047, 0.933),
              Color.hsl(283, 0.044, 0.913),
              Color.hsl(278, 0.041, 0.891),
              Color.hsl(271, 0.039, 0.863),
              Color.hsl(255, 0.037, 0.788),
              Color.hsl(252, 0.040, 0.573),
              Color.hsl(253, 0.035, 0.535),
              Color.hsl(252, 0.040, 0.448),
              Color.hsl(260, 0.250, 0.110),
        )
    /** [Radix Colors] Collection: mauveA */
    @JVMStatic
    val mauveA =
        listOf(
             Color.hsl(300, 0.893, 0.183, 0.012),
             Color.hsl(300, 0.781, 0.090, 0.028),
             Color.hsl(300, 0.995, 0.077, 0.051),
             Color.hsl(270, 0.905, 0.061, 0.071),
             Color.hsl(270, 0.830, 0.052, 0.091),
             Color.hsl(300, 0.935, 0.037, 0.114),
             Color.hsl(270, 0.826, 0.033, 0.142),
             Color.hsl(255, 0.952, 0.037, 0.220),
             Color.hsl(255, 0.948, 0.037, 0.444),
             Color.hsl(253, 0.965, 0.038, 0.483),
             Color.hsl(247, 0.979, 0.032, 0.569),
             Color.hsl(261, 0.987, 0.030, 0.918),
        )
    /** [Radix Colors] Collection: mauveDark */
    @JVMStatic
    val mauveDark =
        listOf(
              Color.hsl(246, 0.060, 0.090),
              Color.hsl(240, 0.051, 0.116),
              Color.hsl(241, 0.050, 0.143),
              Color.hsl(242, 0.049, 0.165),
              Color.hsl(243, 0.049, 0.188),
              Color.hsl(244, 0.049, 0.215),
              Color.hsl(245, 0.049, 0.254),
              Color.hsl(247, 0.048, 0.325),
              Color.hsl(252, 0.040, 0.452),
              Color.hsl(247, 0.034, 0.507),
              Color.hsl(253, 0.040, 0.637),
              Color.hsl(256, 0.060, 0.932),
        )
    /** [Radix Colors] Collection: mauveDarkA */
    @JVMStatic
    val mauveDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(240, 0.767, 0.912, 0.031),
             Color.hsl(240, 0.860, 0.958, 0.061),
             Color.hsl(240, 0.918, 0.947, 0.087),
             Color.hsl(240, 0.915, 0.958, 0.113),
             Color.hsl(240, 0.920, 0.938, 0.148),
             Color.hsl(240, 0.948, 0.953, 0.191),
             Color.hsl(249, 0.981, 0.952, 0.273),
             Color.hsl(248, 0.976, 0.962, 0.416),
             Color.hsl(248, 0.955, 0.966, 0.477),
             Color.hsl(250, 0.980, 0.980, 0.615),
             Color.hsl(240, 0.939, 0.996, 0.931),
        )
    /** [Radix Colors] Collection: mint */
    @JVMStatic
    val mint =
        listOf(
              Color.hsl(165, 0.800, 0.988),
              Color.hsl(164, 0.882, 0.967),
              Color.hsl(164, 0.766, 0.933),
              Color.hsl(165, 0.688, 0.895),
              Color.hsl(165, 0.606, 0.845),
              Color.hsl(165, 0.535, 0.769),
              Color.hsl(166, 0.507, 0.661),
              Color.hsl(168, 0.528, 0.510),
              Color.hsl(167, 0.650, 0.660),
              Color.hsl(167, 0.593, 0.631),
              Color.hsl(172, 0.720, 0.285),
              Color.hsl(172, 0.700, 0.120),
        )
    /** [Radix Colors] Collection: mintA */
    @JVMStatic
    val mintA =
        listOf(
             Color.hsl(168, 0.954, 0.428, 0.024),
             Color.hsl(164, 0.991, 0.471, 0.063),
             Color.hsl(164, 0.993, 0.435, 0.118),
             Color.hsl(164, 0.993, 0.413, 0.177),
             Color.hsl(165, 0.990, 0.375, 0.248),
             Color.hsl(165, 1.000, 0.350, 0.353),
             Color.hsl(166, 0.999, 0.335, 0.510),
             Color.hsl(168, 0.996, 0.346, 0.750),
             Color.hsl(167, 0.999, 0.395, 0.561),
             Color.hsl(167, 0.997, 0.374, 0.589),
             Color.hsl(172, 0.998, 0.224, 0.922),
             Color.hsl(172, 0.997, 0.088, 0.965),
        )
    /** [Radix Colors] Collection: mintDark */
    @JVMStatic
    val mintDark =
        listOf(
              Color.hsl(173, 0.500, 0.066),
              Color.hsl(176, 0.730, 0.073),
              Color.hsl(175, 0.793, 0.089),
              Color.hsl(174, 0.848, 0.103),
              Color.hsl(174, 0.902, 0.119),
              Color.hsl(173, 0.960, 0.138),
              Color.hsl(172, 1.000, 0.168),
              Color.hsl(170, 1.000, 0.214),
              Color.hsl(167, 0.650, 0.660),
              Color.hsl(163, 0.800, 0.770),
              Color.hsl(167, 0.700, 0.480),
              Color.hsl(165, 0.800, 0.948),
        )
    /** [Radix Colors] Collection: mintDarkA */
    @JVMStatic
    val mintDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(180, 1.000, 0.492, 0.031),
             Color.hsl(176, 1.000, 0.497, 0.070),
             Color.hsl(173, 1.000, 0.497, 0.105),
             Color.hsl(173, 1.000, 0.498, 0.144),
             Color.hsl(172, 1.000, 0.498, 0.192),
             Color.hsl(171, 1.000, 0.499, 0.266),
             Color.hsl(169, 1.000, 0.499, 0.366),
             Color.hsl(167, 0.998, 0.750, 0.870),
             Color.hsl(163, 0.999, 0.807, 0.948),
             Color.hsl(167, 0.999, 0.587, 0.796),
             Color.hsl(169, 1.000, 0.962, 0.980),
        )
    /** [Radix Colors] Collection: olive */
    @JVMStatic
    val olive =
        listOf(
              Color.hsl(110, 0.200, 0.990),
              Color.hsl(120, 0.167, 0.976),
              Color.hsl(119, 0.101, 0.952),
              Color.hsl(118, 0.081, 0.930),
              Color.hsl(117, 0.071, 0.908),
              Color.hsl(115, 0.064, 0.885),
              Color.hsl(114, 0.059, 0.854),
              Color.hsl(110, 0.052, 0.773),
              Color.hsl(110, 0.035, 0.555),
              Color.hsl(111, 0.028, 0.517),
              Color.hsl(110, 0.030, 0.430),
              Color.hsl(110, 0.250, 0.095),
        )
    /** [Radix Colors] Collection: oliveA */
    @JVMStatic
    val oliveA =
        listOf(
             Color.hsl(120, 0.893, 0.183, 0.012),
             Color.hsl(120, 0.877, 0.160, 0.028),
             Color.hsl(120, 0.995, 0.077, 0.051),
             Color.hsl(120, 0.923, 0.085, 0.075),
             Color.hsl(120, 0.860, 0.069, 0.099),
             Color.hsl(120, 0.948, 0.068, 0.122),
             Color.hsl(120, 0.993, 0.052, 0.153),
             Color.hsl(110, 0.938, 0.052, 0.240),
             Color.hsl(111, 0.987, 0.030, 0.459),
             Color.hsl(111, 0.935, 0.029, 0.499),
             Color.hsl(111, 0.952, 0.025, 0.585),
             Color.hsl(110, 0.976, 0.026, 0.930),
        )
    /** [Radix Colors] Collection: oliveDark */
    @JVMStatic
    val oliveDark =
        listOf(
              Color.hsl(110, 0.050, 0.086),
              Color.hsl(105, 0.074, 0.106),
              Color.hsl(106, 0.064, 0.131),
              Color.hsl(106, 0.058, 0.153),
              Color.hsl(107, 0.053, 0.174),
              Color.hsl(107, 0.049, 0.199),
              Color.hsl(108, 0.044, 0.236),
              Color.hsl(110, 0.038, 0.306),
              Color.hsl(110, 0.060, 0.425),
              Color.hsl(111, 0.048, 0.482),
              Color.hsl(110, 0.050, 0.618),
              Color.hsl(110, 0.060, 0.930),
        )
    /** [Radix Colors] Collection: oliveDarkA */
    @JVMStatic
    val oliveDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(91, 0.970, 0.840, 0.026),
             Color.hsl(101, 0.874, 0.877, 0.057),
             Color.hsl(92, 0.918, 0.941, 0.078),
             Color.hsl(101, 0.926, 0.935, 0.104),
             Color.hsl(102, 0.911, 0.946, 0.130),
             Color.hsl(102, 0.925, 0.959, 0.173),
             Color.hsl(107, 1.000, 0.965, 0.250),
             Color.hsl(110, 0.983, 0.941, 0.397),
             Color.hsl(109, 0.996, 0.953, 0.457),
             Color.hsl(113, 0.953, 0.972, 0.600),
             Color.hsl(120, 0.935, 0.996, 0.927),
        )
    /** [Radix Colors] Collection: orange */
    @JVMStatic
    val orange =
        listOf(
              Color.hsl(24, 0.700, 0.990),
              Color.hsl(24, 0.833, 0.976),
              Color.hsl(24, 1.000, 0.953),
              Color.hsl(25, 1.000, 0.922),
              Color.hsl(25, 1.000, 0.882),
              Color.hsl(25, 1.000, 0.828),
              Color.hsl(24, 1.000, 0.753),
              Color.hsl(24, 0.945, 0.643),
              Color.hsl(24, 0.940, 0.500),
              Color.hsl(24, 1.000, 0.465),
              Color.hsl(24, 1.000, 0.370),
              Color.hsl(15, 0.600, 0.170),
        )
    /** [Radix Colors] Collection: orangeA */
    @JVMStatic
    val orangeA =
        listOf(
             Color.hsl(20, 0.949, 0.387, 0.016),
             Color.hsl(24, 0.958, 0.465, 0.044),
             Color.hsl(25, 1.000, 0.505, 0.095),
             Color.hsl(26, 1.000, 0.500, 0.157),
             Color.hsl(25, 1.000, 0.501, 0.236),
             Color.hsl(25, 1.000, 0.501, 0.346),
             Color.hsl(24, 1.000, 0.501, 0.495),
             Color.hsl(24, 0.997, 0.487, 0.695),
             Color.hsl(24, 0.999, 0.484, 0.969),
             Color.hsl(23, 1.000, 0.464, 0.980),
             Color.hsl(23, 1.000, 0.368, 0.980),
             Color.hsl(15, 0.994, 0.110, 0.934),
        )
    /** [Radix Colors] Collection: orangeDark */
    @JVMStatic
    val orangeDark =
        listOf(
              Color.hsl(30, 0.700, 0.072),
              Color.hsl(28, 1.000, 0.084),
              Color.hsl(26, 0.911, 0.116),
              Color.hsl(25, 0.883, 0.141),
              Color.hsl(24, 0.876, 0.166),
              Color.hsl(24, 0.886, 0.198),
              Color.hsl(24, 0.924, 0.240),
              Color.hsl(25, 1.000, 0.290),
              Color.hsl(24, 0.940, 0.500),
              Color.hsl(24, 1.000, 0.585),
              Color.hsl(24, 1.000, 0.622),
              Color.hsl(24, 0.970, 0.932),
        )
    /** [Radix Colors] Collection: orangeDarkA */
    @JVMStatic
    val orangeDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(13, 1.000, 0.497, 0.054),
             Color.hsl(20, 1.000, 0.497, 0.117),
             Color.hsl(23, 1.000, 0.498, 0.166),
             Color.hsl(23, 0.994, 0.501, 0.215),
             Color.hsl(23, 0.998, 0.511, 0.286),
             Color.hsl(23, 0.997, 0.506, 0.389),
             Color.hsl(24, 1.000, 0.499, 0.523),
             Color.hsl(24, 0.999, 0.516, 0.965),
             Color.hsl(25, 1.000, 0.586, 0.980),
             Color.hsl(24, 1.000, 0.624, 0.980),
             Color.hsl(26, 1.000, 0.942, 0.980),
        )
    /** [Radix Colors] Collection: pink */
    @JVMStatic
    val pink =
        listOf(
              Color.hsl(322, 1.000, 0.994),
              Color.hsl(323, 1.000, 0.984),
              Color.hsl(323, 0.863, 0.965),
              Color.hsl(323, 0.787, 0.942),
              Color.hsl(323, 0.722, 0.911),
              Color.hsl(323, 0.663, 0.866),
              Color.hsl(323, 0.620, 0.801),
              Color.hsl(323, 0.603, 0.724),
              Color.hsl(322, 0.650, 0.545),
              Color.hsl(322, 0.639, 0.507),
              Color.hsl(322, 0.750, 0.460),
              Color.hsl(320, 0.700, 0.135),
        )
    /** [Radix Colors] Collection: pinkA */
    @JVMStatic
    val pinkA =
        listOf(
             Color.hsl(320, 1.000, 0.510, 0.012),
             Color.hsl(323, 1.000, 0.510, 0.032),
             Color.hsl(323, 0.989, 0.473, 0.067),
             Color.hsl(323, 0.999, 0.443, 0.102),
             Color.hsl(324, 0.999, 0.423, 0.153),
             Color.hsl(323, 0.995, 0.396, 0.224),
             Color.hsl(323, 0.997, 0.385, 0.322),
             Color.hsl(323, 0.995, 0.377, 0.444),
             Color.hsl(322, 0.997, 0.393, 0.750),
             Color.hsl(322, 1.000, 0.391, 0.808),
             Color.hsl(322, 0.998, 0.390, 0.887),
             Color.hsl(321, 0.998, 0.100, 0.961),
        )
    /** [Radix Colors] Collection: pinkDark */
    @JVMStatic
    val pinkDark =
        listOf(
              Color.hsl(318, 0.250, 0.096),
              Color.hsl(319, 0.322, 0.116),
              Color.hsl(319, 0.410, 0.160),
              Color.hsl(320, 0.454, 0.187),
              Color.hsl(320, 0.490, 0.211),
              Color.hsl(321, 0.536, 0.244),
              Color.hsl(321, 0.611, 0.297),
              Color.hsl(322, 0.749, 0.375),
              Color.hsl(322, 0.650, 0.545),
              Color.hsl(323, 0.728, 0.592),
              Color.hsl(325, 0.900, 0.664),
              Color.hsl(322, 0.900, 0.958),
        )
    /** [Radix Colors] Collection: pinkDarkA */
    @JVMStatic
    val pinkDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(320, 0.981, 0.641, 0.036),
             Color.hsl(320, 0.991, 0.631, 0.121),
             Color.hsl(320, 0.995, 0.627, 0.170),
             Color.hsl(319, 0.997, 0.615, 0.219),
             Color.hsl(322, 0.994, 0.608, 0.291),
             Color.hsl(321, 0.996, 0.587, 0.407),
             Color.hsl(322, 0.997, 0.554, 0.608),
             Color.hsl(322, 1.000, 0.646, 0.817),
             Color.hsl(323, 1.000, 0.663, 0.875),
             Color.hsl(325, 0.999, 0.686, 0.960),
             Color.hsl(314, 1.000, 0.969, 0.980),
        )
    /** [Radix Colors] Collection: plum */
    @JVMStatic
    val plum =
        listOf(
              Color.hsl(292, 0.900, 0.994),
              Color.hsl(300, 1.000, 0.986),
              Color.hsl(299, 0.712, 0.964),
              Color.hsl(299, 0.620, 0.938),
              Color.hsl(298, 0.561, 0.905),
              Color.hsl(296, 0.513, 0.858),
              Color.hsl(295, 0.482, 0.789),
              Color.hsl(292, 0.477, 0.708),
              Color.hsl(292, 0.450, 0.510),
              Color.hsl(292, 0.502, 0.469),
              Color.hsl(292, 0.600, 0.425),
              Color.hsl(291, 0.660, 0.140),
        )
    /** [Radix Colors] Collection: plumA */
    @JVMStatic
    val plumA =
        listOf(
             Color.hsl(280, 1.000, 0.510, 0.012),
             Color.hsl(300, 1.000, 0.510, 0.028),
             Color.hsl(300, 0.990, 0.409, 0.063),
             Color.hsl(300, 0.999, 0.385, 0.102),
             Color.hsl(298, 0.982, 0.359, 0.150),
             Color.hsl(297, 0.996, 0.337, 0.216),
             Color.hsl(295, 0.997, 0.326, 0.314),
             Color.hsl(292, 0.996, 0.324, 0.432),
             Color.hsl(292, 0.999, 0.310, 0.710),
             Color.hsl(292, 0.999, 0.308, 0.765),
             Color.hsl(292, 0.998, 0.307, 0.832),
             Color.hsl(291, 0.999, 0.097, 0.953),
        )
    /** [Radix Colors] Collection: plumDark */
    @JVMStatic
    val plumDark =
        listOf(
              Color.hsl(301, 0.200, 0.094),
              Color.hsl(300, 0.298, 0.112),
              Color.hsl(298, 0.344, 0.153),
              Color.hsl(297, 0.368, 0.183),
              Color.hsl(296, 0.385, 0.211),
              Color.hsl(295, 0.404, 0.247),
              Color.hsl(294, 0.427, 0.306),
              Color.hsl(292, 0.451, 0.400),
              Color.hsl(292, 0.450, 0.510),
              Color.hsl(295, 0.500, 0.554),
              Color.hsl(300, 0.600, 0.620),
              Color.hsl(296, 0.740, 0.957),
        )
    /** [Radix Colors] Collection: plumDarkA */
    @JVMStatic
    val plumDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(300, 0.964, 0.584, 0.036),
             Color.hsl(300, 0.994, 0.671, 0.102),
             Color.hsl(295, 0.998, 0.663, 0.155),
             Color.hsl(295, 0.994, 0.671, 0.204),
             Color.hsl(294, 0.990, 0.678, 0.262),
             Color.hsl(294, 0.999, 0.677, 0.363),
             Color.hsl(292, 0.998, 0.675, 0.527),
             Color.hsl(292, 0.999, 0.692, 0.695),
             Color.hsl(295, 0.999, 0.708, 0.748),
             Color.hsl(300, 0.998, 0.729, 0.828),
             Color.hsl(300, 1.000, 0.971, 0.980),
        )
    /** [Radix Colors] Collection: purple */
    @JVMStatic
    val purple =
        listOf(
              Color.hsl(280, 0.650, 0.994),
              Color.hsl(276, 1.000, 0.990),
              Color.hsl(276, 0.831, 0.970),
              Color.hsl(275, 0.764, 0.947),
              Color.hsl(275, 0.708, 0.918),
              Color.hsl(274, 0.654, 0.878),
              Color.hsl(273, 0.610, 0.817),
              Color.hsl(272, 0.600, 0.735),
              Color.hsl(272, 0.510, 0.540),
              Color.hsl(272, 0.468, 0.503),
              Color.hsl(272, 0.500, 0.458),
              Color.hsl(272, 0.660, 0.160),
        )
    /** [Radix Colors] Collection: purpleA */
    @JVMStatic
    val purpleA =
        listOf(
             Color.hsl(300, 0.943, 0.346, 0.012),
             Color.hsl(276, 1.000, 0.510, 0.020),
             Color.hsl(277, 0.996, 0.465, 0.055),
             Color.hsl(274, 0.979, 0.443, 0.095),
             Color.hsl(276, 0.986, 0.420, 0.142),
             Color.hsl(275, 1.000, 0.392, 0.200),
             Color.hsl(273, 0.992, 0.382, 0.295),
             Color.hsl(272, 0.997, 0.376, 0.424),
             Color.hsl(272, 0.996, 0.340, 0.695),
             Color.hsl(272, 0.997, 0.320, 0.730),
             Color.hsl(272, 0.998, 0.297, 0.773),
             Color.hsl(272, 0.992, 0.113, 0.946),
        )
    /** [Radix Colors] Collection: purpleDark */
    @JVMStatic
    val purpleDark =
        listOf(
              Color.hsl(284, 0.200, 0.096),
              Color.hsl(283, 0.300, 0.118),
              Color.hsl(281, 0.375, 0.165),
              Color.hsl(280, 0.412, 0.200),
              Color.hsl(279, 0.438, 0.233),
              Color.hsl(277, 0.464, 0.275),
              Color.hsl(275, 0.493, 0.346),
              Color.hsl(272, 0.521, 0.459),
              Color.hsl(272, 0.510, 0.540),
              Color.hsl(273, 0.573, 0.591),
              Color.hsl(275, 0.800, 0.710),
              Color.hsl(279, 0.750, 0.957),
        )
    /** [Radix Colors] Collection: purpleDarkA */
    @JVMStatic
    val purpleDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(280, 0.965, 0.575, 0.045),
             Color.hsl(279, 0.987, 0.628, 0.129),
             Color.hsl(279, 0.991, 0.640, 0.191),
             Color.hsl(278, 0.998, 0.642, 0.248),
             Color.hsl(276, 0.996, 0.646, 0.328),
             Color.hsl(274, 0.999, 0.646, 0.456),
             Color.hsl(272, 0.997, 0.646, 0.660),
             Color.hsl(272, 0.999, 0.691, 0.748),
             Color.hsl(273, 1.000, 0.713, 0.801),
             Color.hsl(275, 0.999, 0.753, 0.934),
             Color.hsl(286, 1.000, 0.971, 0.980),
        )
    /** [Radix Colors] Collection: red */
    @JVMStatic
    val red =
        listOf(
              Color.hsl(359, 1.000, 0.994),
              Color.hsl(359, 1.000, 0.986),
              Color.hsl(360, 1.000, 0.968),
              Color.hsl(360, 0.979, 0.948),
              Color.hsl(360, 0.902, 0.919),
              Color.hsl(360, 0.817, 0.878),
              Color.hsl(359, 0.742, 0.817),
              Color.hsl(359, 0.695, 0.743),
              Color.hsl(358, 0.750, 0.590),
              Color.hsl(358, 0.694, 0.552),
              Color.hsl(358, 0.650, 0.487),
              Color.hsl(354, 0.500, 0.146),
        )
    /** [Radix Colors] Collection: redA */
    @JVMStatic
    val redA =
        listOf(
             Color.hsl(0, 1.000, 0.510, 0.012),
             Color.hsl(0, 1.000, 0.510, 0.032),
             Color.hsl(0, 1.000, 0.502, 0.063),
             Color.hsl(0, 1.000, 0.500, 0.102),
             Color.hsl(0, 0.999, 0.475, 0.153),
             Color.hsl(0, 0.995, 0.449, 0.224),
             Color.hsl(359, 0.997, 0.427, 0.318),
             Color.hsl(359, 0.996, 0.411, 0.436),
             Color.hsl(358, 0.999, 0.429, 0.718),
             Color.hsl(358, 0.999, 0.410, 0.761),
             Color.hsl(358, 0.998, 0.383, 0.832),
             Color.hsl(355, 0.993, 0.079, 0.926),
        )
    /** [Radix Colors] Collection: redDark */
    @JVMStatic
    val redDark =
        listOf(
              Color.hsl(353, 0.230, 0.098),
              Color.hsl(357, 0.344, 0.120),
              Color.hsl(356, 0.434, 0.164),
              Color.hsl(356, 0.476, 0.192),
              Color.hsl(356, 0.511, 0.219),
              Color.hsl(356, 0.552, 0.259),
              Color.hsl(357, 0.602, 0.318),
              Color.hsl(358, 0.650, 0.404),
              Color.hsl(358, 0.750, 0.590),
              Color.hsl(358, 0.853, 0.640),
              Color.hsl(358, 1.000, 0.695),
              Color.hsl(351, 0.890, 0.960),
        )
    /** [Radix Colors] Collection: redDarkA */
    @JVMStatic
    val redDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(5, 0.985, 0.538, 0.045),
             Color.hsl(359, 0.991, 0.611, 0.130),
             Color.hsl(358, 0.988, 0.610, 0.184),
             Color.hsl(357, 0.996, 0.603, 0.237),
             Color.hsl(358, 0.996, 0.603, 0.322),
             Color.hsl(357, 1.000, 0.595, 0.442),
             Color.hsl(358, 0.998, 0.591, 0.621),
             Color.hsl(358, 1.000, 0.655, 0.884),
             Color.hsl(358, 1.000, 0.675, 0.942),
             Color.hsl(358, 1.000, 0.697, 0.980),
             Color.hsl(352, 1.000, 0.971, 0.980),
        )
    /** [Radix Colors] Collection: sage */
    @JVMStatic
    val sage =
        listOf(
              Color.hsl(155, 0.300, 0.988),
              Color.hsl(150, 0.167, 0.976),
              Color.hsl(151, 0.106, 0.952),
              Color.hsl(151, 0.088, 0.930),
              Color.hsl(151, 0.078, 0.908),
              Color.hsl(152, 0.072, 0.884),
              Color.hsl(153, 0.067, 0.853),
              Color.hsl(154, 0.061, 0.775),
              Color.hsl(155, 0.035, 0.555),
              Color.hsl(154, 0.028, 0.517),
              Color.hsl(155, 0.030, 0.430),
              Color.hsl(155, 0.240, 0.090),
        )
    /** [Radix Colors] Collection: sageA */
    @JVMStatic
    val sageA =
        listOf(
             Color.hsl(150, 0.926, 0.265, 0.016),
             Color.hsl(150, 0.877, 0.160, 0.028),
             Color.hsl(160, 0.984, 0.109, 0.055),
             Color.hsl(140, 0.923, 0.085, 0.075),
             Color.hsl(160, 0.860, 0.069, 0.099),
             Color.hsl(156, 0.951, 0.082, 0.126),
             Color.hsl(156, 0.986, 0.063, 0.157),
             Color.hsl(154, 0.946, 0.060, 0.240),
             Color.hsl(154, 0.987, 0.030, 0.459),
             Color.hsl(154, 0.935, 0.029, 0.499),
             Color.hsl(154, 0.952, 0.025, 0.585),
             Color.hsl(158, 0.970, 0.024, 0.934),
        )
    /** [Radix Colors] Collection: sageDark */
    @JVMStatic
    val sageDark =
        listOf(
              Color.hsl(155, 0.070, 0.084),
              Color.hsl(150, 0.074, 0.106),
              Color.hsl(150, 0.067, 0.131),
              Color.hsl(150, 0.064, 0.153),
              Color.hsl(150, 0.061, 0.174),
              Color.hsl(150, 0.058, 0.199),
              Color.hsl(150, 0.055, 0.236),
              Color.hsl(150, 0.051, 0.306),
              Color.hsl(155, 0.060, 0.425),
              Color.hsl(153, 0.048, 0.482),
              Color.hsl(155, 0.050, 0.618),
              Color.hsl(155, 0.060, 0.930),
        )
    /** [Radix Colors] Collection: sageDarkA */
    @JVMStatic
    val sageDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(123, 0.944, 0.914, 0.026),
             Color.hsl(123, 0.829, 0.910, 0.057),
             Color.hsl(124, 0.979, 0.945, 0.082),
             Color.hsl(125, 0.900, 0.952, 0.104),
             Color.hsl(142, 0.951, 0.948, 0.134),
             Color.hsl(143, 0.928, 0.957, 0.173),
             Color.hsl(146, 0.947, 0.953, 0.255),
             Color.hsl(151, 0.982, 0.944, 0.397),
             Color.hsl(148, 0.995, 0.955, 0.457),
             Color.hsl(152, 0.951, 0.973, 0.600),
             Color.hsl(149, 0.933, 0.996, 0.927),
        )
    /** [Radix Colors] Collection: sand */
    @JVMStatic
    val sand =
        listOf(
              Color.hsl(50, 0.200, 0.990),
              Color.hsl(60, 0.077, 0.975),
              Color.hsl(59, 0.065, 0.951),
              Color.hsl(58, 0.061, 0.929),
              Color.hsl(57, 0.060, 0.907),
              Color.hsl(56, 0.059, 0.884),
              Color.hsl(55, 0.059, 0.852),
              Color.hsl(51, 0.060, 0.771),
              Color.hsl(50, 0.020, 0.557),
              Color.hsl(55, 0.017, 0.519),
              Color.hsl(50, 0.020, 0.431),
              Color.hsl(50, 0.060, 0.100),
        )
    /** [Radix Colors] Collection: sandA */
    @JVMStatic
    val sandA =
        listOf(
             Color.hsl(60, 0.893, 0.183, 0.012),
             Color.hsl(60, 0.781, 0.090, 0.028),
             Color.hsl(60, 0.990, 0.039, 0.051),
             Color.hsl(60, 0.889, 0.059, 0.075),
             Color.hsl(60, 0.860, 0.069, 0.099),
             Color.hsl(60, 0.932, 0.052, 0.122),
             Color.hsl(60, 0.983, 0.051, 0.157),
             Color.hsl(51, 0.941, 0.060, 0.244),
             Color.hsl(60, 0.998, 0.017, 0.451),
             Color.hsl(60, 0.907, 0.018, 0.491),
             Color.hsl(45, 0.937, 0.015, 0.577),
             Color.hsl(60, 0.980, 0.007, 0.906),
        )
    /** [Radix Colors] Collection: sandDark */
    @JVMStatic
    val sandDark =
        listOf(
              Color.hsl(61, 0.020, 0.083),
              Color.hsl(60, 0.037, 0.106),
              Color.hsl(58, 0.037, 0.131),
              Color.hsl(57, 0.036, 0.153),
              Color.hsl(56, 0.037, 0.174),
              Color.hsl(55, 0.037, 0.199),
              Color.hsl(53, 0.037, 0.236),
              Color.hsl(50, 0.038, 0.306),
              Color.hsl(50, 0.040, 0.427),
              Color.hsl(52, 0.031, 0.483),
              Color.hsl(50, 0.040, 0.618),
              Color.hsl(56, 0.040, 0.928),
        )
    /** [Radix Colors] Collection: sandDarkA */
    @JVMStatic
    val sandDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(60, 0.898, 0.914, 0.026),
             Color.hsl(60, 0.955, 0.925, 0.056),
             Color.hsl(60, 0.756, 0.964, 0.078),
             Color.hsl(60, 0.819, 0.952, 0.104),
             Color.hsl(41, 0.876, 0.948, 0.134),
             Color.hsl(60, 0.954, 0.962, 0.172),
             Color.hsl(49, 0.935, 0.957, 0.254),
             Color.hsl(52, 0.973, 0.962, 0.391),
             Color.hsl(52, 0.978, 0.967, 0.451),
             Color.hsl(51, 0.970, 0.978, 0.597),
             Color.hsl(60, 0.887, 0.998, 0.923),
        )
    /** [Radix Colors] Collection: sky */
    @JVMStatic
    val sky =
        listOf(
              Color.hsl(193, 1.000, 0.988),
              Color.hsl(193, 1.000, 0.973),
              Color.hsl(193, 0.990, 0.947),
              Color.hsl(193, 0.914, 0.914),
              Color.hsl(194, 0.820, 0.866),
              Color.hsl(194, 0.741, 0.795),
              Color.hsl(194, 0.723, 0.696),
              Color.hsl(193, 0.779, 0.539),
              Color.hsl(193, 0.980, 0.700),
              Color.hsl(193, 0.870, 0.665),
              Color.hsl(195, 1.000, 0.315),
              Color.hsl(195, 1.000, 0.130),
        )
    /** [Radix Colors] Collection: skyA */
    @JVMStatic
    val skyA =
        listOf(
             Color.hsl(190, 1.000, 0.510, 0.024),
             Color.hsl(193, 1.000, 0.501, 0.055),
             Color.hsl(193, 1.000, 0.501, 0.106),
             Color.hsl(194, 0.996, 0.477, 0.165),
             Color.hsl(194, 0.992, 0.454, 0.244),
             Color.hsl(194, 0.999, 0.423, 0.357),
             Color.hsl(194, 0.998, 0.422, 0.526),
             Color.hsl(193, 0.999, 0.438, 0.820),
             Color.hsl(193, 0.997, 0.494, 0.593),
             Color.hsl(193, 0.998, 0.466, 0.628),
             Color.hsl(196, 1.000, 0.312, 0.980),
             Color.hsl(196, 1.000, 0.122, 0.980),
        )
    /** [Radix Colors] Collection: skyDark */
    @JVMStatic
    val skyDark =
        listOf(
              Color.hsl(205, 0.450, 0.086),
              Color.hsl(202, 0.714, 0.096),
              Color.hsl(201, 0.746, 0.122),
              Color.hsl(201, 0.774, 0.144),
              Color.hsl(200, 0.803, 0.165),
              Color.hsl(200, 0.841, 0.189),
              Color.hsl(199, 0.902, 0.221),
              Color.hsl(198, 1.000, 0.261),
              Color.hsl(193, 0.980, 0.700),
              Color.hsl(192, 1.000, 0.770),
              Color.hsl(192, 0.850, 0.558),
              Color.hsl(198, 0.980, 0.958),
        )
    /** [Radix Colors] Collection: skyDarkA */
    @JVMStatic
    val skyDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(208, 1.000, 0.498, 0.045),
             Color.hsl(201, 1.000, 0.498, 0.099),
             Color.hsl(201, 1.000, 0.500, 0.148),
             Color.hsl(200, 1.000, 0.498, 0.198),
             Color.hsl(199, 1.000, 0.499, 0.256),
             Color.hsl(199, 1.000, 0.499, 0.337),
             Color.hsl(199, 1.000, 0.500, 0.453),
             Color.hsl(192, 1.000, 0.708, 0.980),
             Color.hsl(190, 1.000, 0.776, 0.980),
             Color.hsl(192, 0.999, 0.596, 0.924),
             Color.hsl(189, 1.000, 0.968, 0.980),
        )
    /** [Radix Colors] Collection: slate */
    @JVMStatic
    val slate =
        listOf(
              Color.hsl(206, 0.300, 0.988),
              Color.hsl(210, 0.167, 0.976),
              Color.hsl(209, 0.133, 0.953),
              Color.hsl(209, 0.122, 0.932),
              Color.hsl(208, 0.117, 0.911),
              Color.hsl(208, 0.113, 0.889),
              Color.hsl(207, 0.111, 0.859),
              Color.hsl(205, 0.107, 0.780),
              Color.hsl(206, 0.060, 0.561),
              Color.hsl(206, 0.058, 0.523),
              Color.hsl(206, 0.060, 0.435),
              Color.hsl(206, 0.240, 0.090),
        )
    /** [Radix Colors] Collection: slateA */
    @JVMStatic
    val slateA =
        listOf(
             Color.hsl(210, 0.926, 0.265, 0.016),
             Color.hsl(210, 0.877, 0.160, 0.028),
             Color.hsl(210, 0.988, 0.144, 0.055),
             Color.hsl(210, 0.941, 0.111, 0.075),
             Color.hsl(216, 0.911, 0.109, 0.099),
             Color.hsl(206, 0.964, 0.113, 0.126),
             Color.hsl(210, 0.991, 0.101, 0.157),
             Color.hsl(205, 0.965, 0.100, 0.244),
             Color.hsl(206, 0.988, 0.059, 0.467),
             Color.hsl(206, 0.996, 0.054, 0.506),
             Color.hsl(206, 0.970, 0.048, 0.593),
             Color.hsl(202, 0.970, 0.024, 0.934),
        )
    /** [Radix Colors] Collection: slateDark */
    @JVMStatic
    val slateDark =
        listOf(
              Color.hsl(200, 0.070, 0.088),
              Color.hsl(195, 0.071, 0.110),
              Color.hsl(197, 0.068, 0.136),
              Color.hsl(198, 0.066, 0.158),
              Color.hsl(199, 0.064, 0.179),
              Color.hsl(201, 0.062, 0.205),
              Color.hsl(203, 0.060, 0.243),
              Color.hsl(207, 0.056, 0.316),
              Color.hsl(206, 0.060, 0.439),
              Color.hsl(206, 0.052, 0.495),
              Color.hsl(206, 0.060, 0.630),
              Color.hsl(210, 0.060, 0.930),
        )
    /** [Radix Colors] Collection: slateDarkA */
    @JVMStatic
    val slateDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(181, 0.989, 0.918, 0.026),
             Color.hsl(182, 0.867, 0.914, 0.057),
             Color.hsl(209, 0.867, 0.939, 0.083),
             Color.hsl(200, 0.903, 0.934, 0.109),
             Color.hsl(209, 0.953, 0.935, 0.139),
             Color.hsl(204, 0.985, 0.939, 0.182),
             Color.hsl(209, 0.940, 0.947, 0.265),
             Color.hsl(207, 0.973, 0.940, 0.412),
             Color.hsl(209, 0.994, 0.952, 0.472),
             Color.hsl(208, 0.987, 0.968, 0.615),
             Color.hsl(211, 0.867, 0.996, 0.927),
        )
    /** [Radix Colors] Collection: teal */
    @JVMStatic
    val teal =
        listOf(
              Color.hsl(165, 0.600, 0.988),
              Color.hsl(169, 0.647, 0.967),
              Color.hsl(169, 0.598, 0.940),
              Color.hsl(169, 0.531, 0.902),
              Color.hsl(170, 0.471, 0.850),
              Color.hsl(170, 0.426, 0.779),
              Color.hsl(170, 0.399, 0.681),
              Color.hsl(172, 0.421, 0.525),
              Color.hsl(173, 0.800, 0.360),
              Color.hsl(173, 0.834, 0.325),
              Color.hsl(174, 0.900, 0.252),
              Color.hsl(170, 0.500, 0.125),
        )
    /** [Radix Colors] Collection: tealA */
    @JVMStatic
    val tealA =
        listOf(
             Color.hsl(165, 0.952, 0.412, 0.020),
             Color.hsl(169, 0.995, 0.394, 0.055),
             Color.hsl(167, 0.976, 0.381, 0.095),
             Color.hsl(168, 0.981, 0.346, 0.150),
             Color.hsl(170, 0.994, 0.323, 0.220),
             Color.hsl(170, 0.997, 0.301, 0.314),
             Color.hsl(170, 0.993, 0.287, 0.448),
             Color.hsl(172, 0.998, 0.297, 0.675),
             Color.hsl(173, 0.998, 0.311, 0.930),
             Color.hsl(173, 0.997, 0.287, 0.946),
             Color.hsl(174, 0.998, 0.233, 0.977),
             Color.hsl(171, 0.988, 0.068, 0.938),
        )
    /** [Radix Colors] Collection: tealDark */
    @JVMStatic
    val tealDark =
        listOf(
              Color.hsl(168, 0.480, 0.065),
              Color.hsl(169, 0.778, 0.071),
              Color.hsl(170, 0.761, 0.092),
              Color.hsl(171, 0.758, 0.110),
              Color.hsl(171, 0.757, 0.128),
              Color.hsl(172, 0.758, 0.151),
              Color.hsl(172, 0.767, 0.186),
              Color.hsl(173, 0.802, 0.237),
              Color.hsl(173, 0.800, 0.360),
              Color.hsl(174, 0.839, 0.382),
              Color.hsl(174, 0.900, 0.407),
              Color.hsl(166, 0.730, 0.931),
        )
    /** [Radix Colors] Collection: tealDarkA */
    @JVMStatic
    val tealDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(171, 1.000, 0.492, 0.031),
             Color.hsl(172, 1.000, 0.497, 0.070),
             Color.hsl(175, 1.000, 0.497, 0.105),
             Color.hsl(174, 0.989, 0.501, 0.140),
             Color.hsl(174, 1.000, 0.518, 0.187),
             Color.hsl(173, 0.996, 0.532, 0.257),
             Color.hsl(174, 0.996, 0.533, 0.366),
             Color.hsl(173, 0.999, 0.546, 0.609),
             Color.hsl(174, 0.999, 0.538, 0.670),
             Color.hsl(174, 1.000, 0.520, 0.748),
             Color.hsl(166, 0.986, 0.950, 0.979),
        )
    /** [Radix Colors] Collection: tomato */
    @JVMStatic
    val tomato =
        listOf(
              Color.hsl(10, 1.000, 0.994),
              Color.hsl(8, 1.000, 0.984),
              Color.hsl(8, 1.000, 0.966),
              Color.hsl(8, 1.000, 0.943),
              Color.hsl(8, 0.928, 0.910),
              Color.hsl(9, 0.847, 0.863),
              Color.hsl(10, 0.773, 0.795),
              Color.hsl(10, 0.716, 0.710),
              Color.hsl(10, 0.780, 0.540),
              Color.hsl(10, 0.715, 0.500),
              Color.hsl(10, 0.820, 0.435),
              Color.hsl(10, 0.500, 0.135),
        )
    /** [Radix Colors] Collection: tomatoA */
    @JVMStatic
    val tomatoA =
        listOf(
             Color.hsl(0, 1.000, 0.510, 0.012),
             Color.hsl(8, 1.000, 0.510, 0.032),
             Color.hsl(7, 1.000, 0.502, 0.067),
             Color.hsl(8, 1.000, 0.501, 0.114),
             Color.hsl(7, 0.995, 0.479, 0.173),
             Color.hsl(9, 0.999, 0.462, 0.255),
             Color.hsl(10, 0.998, 0.436, 0.365),
             Color.hsl(10, 0.995, 0.418, 0.499),
             Color.hsl(10, 0.999, 0.438, 0.820),
             Color.hsl(10, 1.000, 0.418, 0.859),
             Color.hsl(10, 0.999, 0.388, 0.922),
             Color.hsl(10, 0.990, 0.074, 0.934),
        )
    /** [Radix Colors] Collection: tomatoDark */
    @JVMStatic
    val tomatoDark =
        listOf(
              Color.hsl(10, 0.230, 0.094),
              Color.hsl(9, 0.448, 0.114),
              Color.hsl(8, 0.520, 0.153),
              Color.hsl(7, 0.563, 0.180),
              Color.hsl(7, 0.601, 0.206),
              Color.hsl(8, 0.648, 0.240),
              Color.hsl(8, 0.712, 0.291),
              Color.hsl(10, 0.802, 0.357),
              Color.hsl(10, 0.780, 0.540),
              Color.hsl(10, 0.817, 0.590),
              Color.hsl(10, 0.850, 0.628),
              Color.hsl(10, 0.890, 0.960),
        )
    /** [Radix Colors] Collection: tomatoDarkA */
    @JVMStatic
    val tomatoDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(5, 1.000, 0.496, 0.058),
             Color.hsl(6, 0.996, 0.549, 0.133),
             Color.hsl(6, 0.992, 0.554, 0.191),
             Color.hsl(6, 0.995, 0.558, 0.244),
             Color.hsl(7, 0.997, 0.559, 0.319),
             Color.hsl(8, 0.998, 0.548, 0.434),
             Color.hsl(10, 0.998, 0.535, 0.598),
             Color.hsl(10, 1.000, 0.597, 0.885),
             Color.hsl(10, 1.000, 0.636, 0.916),
             Color.hsl(10, 0.997, 0.664, 0.939),
             Color.hsl(12, 1.000, 0.971, 0.980),
        )
    /** [Radix Colors] Collection: violet */
    @JVMStatic
    val violet =
        listOf(
              Color.hsl(255, 0.650, 0.994),
              Color.hsl(252, 1.000, 0.990),
              Color.hsl(252, 0.969, 0.974),
              Color.hsl(252, 0.915, 0.955),
              Color.hsl(252, 0.851, 0.930),
              Color.hsl(252, 0.778, 0.894),
              Color.hsl(252, 0.710, 0.837),
              Color.hsl(252, 0.686, 0.763),
              Color.hsl(252, 0.560, 0.575),
              Color.hsl(251, 0.481, 0.535),
              Color.hsl(250, 0.430, 0.480),
              Color.hsl(254, 0.600, 0.185),
        )
    /** [Radix Colors] Collection: violetA */
    @JVMStatic
    val violetA =
        listOf(
             Color.hsl(270, 0.943, 0.346, 0.012),
             Color.hsl(252, 1.000, 0.510, 0.020),
             Color.hsl(254, 1.000, 0.500, 0.051),
             Color.hsl(251, 0.983, 0.482, 0.087),
             Color.hsl(252, 0.990, 0.457, 0.130),
             Color.hsl(251, 0.991, 0.440, 0.189),
             Color.hsl(252, 0.995, 0.417, 0.279),
             Color.hsl(252, 1.000, 0.407, 0.400),
             Color.hsl(252, 0.999, 0.358, 0.663),
             Color.hsl(251, 0.996, 0.325, 0.691),
             Color.hsl(250, 0.998, 0.284, 0.726),
             Color.hsl(254, 0.995, 0.119, 0.926),
        )
    /** [Radix Colors] Collection: violetDark */
    @JVMStatic
    val violetDark =
        listOf(
              Color.hsl(250, 0.200, 0.102),
              Color.hsl(255, 0.303, 0.129),
              Color.hsl(253, 0.370, 0.184),
              Color.hsl(252, 0.401, 0.225),
              Color.hsl(252, 0.422, 0.262),
              Color.hsl(251, 0.443, 0.311),
              Color.hsl(250, 0.468, 0.389),
              Color.hsl(250, 0.518, 0.512),
              Color.hsl(252, 0.560, 0.575),
              Color.hsl(251, 0.632, 0.632),
              Color.hsl(250, 0.950, 0.768),
              Color.hsl(252, 0.870, 0.964),
        )
    /** [Radix Colors] Collection: violetDarkA */
    @JVMStatic
    val violetDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(258, 0.982, 0.610, 0.054),
             Color.hsl(252, 0.988, 0.658, 0.148),
             Color.hsl(253, 0.997, 0.657, 0.219),
             Color.hsl(252, 0.997, 0.664, 0.286),
             Color.hsl(251, 0.997, 0.662, 0.371),
             Color.hsl(250, 0.997, 0.663, 0.514),
             Color.hsl(250, 0.997, 0.661, 0.733),
             Color.hsl(252, 0.999, 0.703, 0.786),
             Color.hsl(251, 0.999, 0.729, 0.844),
             Color.hsl(250, 1.000, 0.779, 0.980),
             Color.hsl(254, 1.000, 0.975, 0.980),
        )
    /** [Radix Colors] Collection: whiteA */
    @JVMStatic
    val whiteA =
        listOf(
             Color.hsl(0, 0.000, 1.000, 0.000),
             Color.hsl(0, 0.000, 1.000, 0.013),
             Color.hsl(0, 0.000, 1.000, 0.034),
             Color.hsl(0, 0.000, 1.000, 0.056),
             Color.hsl(0, 0.000, 1.000, 0.086),
             Color.hsl(0, 0.000, 1.000, 0.124),
             Color.hsl(0, 0.000, 1.000, 0.176),
             Color.hsl(0, 0.000, 1.000, 0.249),
             Color.hsl(0, 0.000, 1.000, 0.386),
             Color.hsl(0, 0.000, 1.000, 0.446),
             Color.hsl(0, 0.000, 1.000, 0.592),
             Color.hsl(0, 0.000, 1.000, 0.923),
        )
    /** [Radix Colors] Collection: yellow */
    @JVMStatic
    val yellow =
        listOf(
              Color.hsl(60, 0.540, 0.985),
              Color.hsl(52, 1.000, 0.955),
              Color.hsl(55, 1.000, 0.909),
              Color.hsl(54, 1.000, 0.866),
              Color.hsl(52, 0.979, 0.820),
              Color.hsl(50, 0.894, 0.761),
              Color.hsl(47, 0.804, 0.680),
              Color.hsl(48, 1.000, 0.461),
              Color.hsl(53, 0.920, 0.500),
              Color.hsl(50, 1.000, 0.485),
              Color.hsl(42, 1.000, 0.290),
              Color.hsl(40, 0.550, 0.135),
        )
    /** [Radix Colors] Collection: yellowA */
    @JVMStatic
    val yellowA =
        listOf(
             Color.hsl(60, 0.943, 0.346, 0.024),
             Color.hsl(52, 1.000, 0.504, 0.091),
             Color.hsl(55, 1.000, 0.502, 0.181),
             Color.hsl(54, 1.000, 0.501, 0.267),
             Color.hsl(52, 0.999, 0.495, 0.357),
             Color.hsl(50, 1.000, 0.474, 0.451),
             Color.hsl(47, 0.998, 0.446, 0.577),
             Color.hsl(48, 1.000, 0.460, 0.980),
             Color.hsl(53, 1.000, 0.480, 0.961),
             Color.hsl(50, 1.000, 0.484, 0.980),
             Color.hsl(42, 1.000, 0.286, 0.980),
             Color.hsl(41, 0.989, 0.080, 0.942),
        )
    /** [Radix Colors] Collection: yellowDark */
    @JVMStatic
    val yellowDark =
        listOf(
              Color.hsl(45, 1.000, 0.055),
              Color.hsl(46, 1.000, 0.067),
              Color.hsl(45, 1.000, 0.087),
              Color.hsl(45, 1.000, 0.104),
              Color.hsl(47, 1.000, 0.121),
              Color.hsl(49, 1.000, 0.143),
              Color.hsl(49, 0.903, 0.184),
              Color.hsl(50, 1.000, 0.220),
              Color.hsl(53, 0.920, 0.500),
              Color.hsl(54, 1.000, 0.680),
              Color.hsl(48, 1.000, 0.470),
              Color.hsl(53, 1.000, 0.910),
        )
    /** [Radix Colors] Collection: yellowDarkA */
    @JVMStatic
    val yellowDarkA =
        listOf(
             Color.hsl(0, 0.000, 0.000, 0.000),
             Color.hsl(49, 1.000, 0.491, 0.027),
             Color.hsl(45, 1.000, 0.497, 0.071),
             Color.hsl(46, 1.000, 0.497, 0.111),
             Color.hsl(47, 1.000, 0.499, 0.150),
             Color.hsl(51, 1.000, 0.498, 0.199),
             Color.hsl(51, 0.998, 0.536, 0.269),
             Color.hsl(51, 1.000, 0.499, 0.371),
             Color.hsl(53, 1.000, 0.520, 0.956),
             Color.hsl(56, 1.000, 0.684, 0.980),
             Color.hsl(48, 1.000, 0.500, 0.934),
             Color.hsl(60, 1.000, 0.918, 0.980),
        )
}
