/**
 * GENERATED FILE: DO NOT EDIT
 * This file was generated by radix-colors-kotlin v1.2.0
 * Visit: https://github.com/eklipse2k8/radix-colors-kotlin for more information.
 */

package com.eklipse2k8.radixcolor

import androidx.compose.ui.graphics.Color

/** [Radix Colors] A gorgeous, accessible color system. */
object RadixColors {
  /** [Radix Colors] Collection: amber */
  val amber =
      listOf(
          Color.hsl(39f, 0.700f, 0.990f),
          Color.hsl(40f, 1.000f, 0.965f),
          Color.hsl(44f, 1.000f, 0.917f),
          Color.hsl(43f, 1.000f, 0.868f),
          Color.hsl(42f, 1.000f, 0.818f),
          Color.hsl(38f, 0.997f, 0.763f),
          Color.hsl(36f, 0.861f, 0.671f),
          Color.hsl(35f, 0.852f, 0.551f),
          Color.hsl(39f, 1.000f, 0.570f),
          Color.hsl(35f, 1.000f, 0.555f),
          Color.hsl(30f, 1.000f, 0.340f),
          Color.hsl(20f, 0.800f, 0.170f),
      )
  /** [Radix Colors] Collection: amberA */
  val amberA =
      listOf(
          Color.hsl(40f, 0.949f, 0.387f, 0.016f),
          Color.hsl(40f, 1.000f, 0.503f, 0.071f),
          Color.hsl(44f, 1.000f, 0.501f, 0.165f),
          Color.hsl(43f, 1.000f, 0.500f, 0.263f),
          Color.hsl(42f, 1.000f, 0.500f, 0.365f),
          Color.hsl(38f, 1.000f, 0.501f, 0.475f),
          Color.hsl(36f, 0.999f, 0.462f, 0.612f),
          Color.hsl(35f, 0.998f, 0.460f, 0.832f),
          Color.hsl(39f, 1.000f, 0.500f, 0.859f),
          Color.hsl(35f, 1.000f, 0.500f, 0.891f),
          Color.hsl(29f, 1.000f, 0.336f, 0.980f),
          Color.hsl(20f, 0.998f, 0.141f, 0.965f),
      )
  /** [Radix Colors] Collection: amberDark */
  val amberDark =
      listOf(
          Color.hsl(36f, 1.000f, 0.061f),
          Color.hsl(35f, 1.000f, 0.076f),
          Color.hsl(32f, 1.000f, 0.102f),
          Color.hsl(32f, 1.000f, 0.124f),
          Color.hsl(33f, 1.000f, 0.146f),
          Color.hsl(35f, 1.000f, 0.171f),
          Color.hsl(35f, 0.910f, 0.216f),
          Color.hsl(36f, 1.000f, 0.255f),
          Color.hsl(39f, 1.000f, 0.570f),
          Color.hsl(43f, 1.000f, 0.640f),
          Color.hsl(39f, 0.900f, 0.498f),
          Color.hsl(39f, 0.970f, 0.932f),
      )
  /** [Radix Colors] Collection: amberDarkA */
  val amberDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(31f, 1.000f, 0.497f, 0.036f),
          Color.hsl(27f, 1.000f, 0.499f, 0.094f),
          Color.hsl(29f, 1.000f, 0.500f, 0.143f),
          Color.hsl(31f, 1.000f, 0.500f, 0.192f),
          Color.hsl(35f, 1.000f, 0.500f, 0.250f),
          Color.hsl(34f, 0.996f, 0.529f, 0.331f),
          Color.hsl(36f, 1.000f, 0.500f, 0.442f),
          Color.hsl(40f, 1.000f, 0.572f, 0.980f),
          Color.hsl(44f, 1.000f, 0.642f, 0.980f),
          Color.hsl(39f, 0.999f, 0.527f, 0.938f),
          Color.hsl(45f, 1.000f, 0.942f, 0.980f),
      )
  /** [Radix Colors] Collection: blackA */
  val blackA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.012f),
          Color.hsl(0f, 0.000f, 0.000f, 0.027f),
          Color.hsl(0f, 0.000f, 0.000f, 0.047f),
          Color.hsl(0f, 0.000f, 0.000f, 0.071f),
          Color.hsl(0f, 0.000f, 0.000f, 0.090f),
          Color.hsl(0f, 0.000f, 0.000f, 0.114f),
          Color.hsl(0f, 0.000f, 0.000f, 0.141f),
          Color.hsl(0f, 0.000f, 0.000f, 0.220f),
          Color.hsl(0f, 0.000f, 0.000f, 0.439f),
          Color.hsl(0f, 0.000f, 0.000f, 0.478f),
          Color.hsl(0f, 0.000f, 0.000f, 0.565f),
          Color.hsl(0f, 0.000f, 0.000f, 0.910f),
      )
  /** [Radix Colors] Collection: blue */
  val blue =
      listOf(
          Color.hsl(206f, 1.000f, 0.992f),
          Color.hsl(210f, 1.000f, 0.980f),
          Color.hsl(209f, 1.000f, 0.965f),
          Color.hsl(210f, 0.988f, 0.940f),
          Color.hsl(209f, 0.950f, 0.901f),
          Color.hsl(209f, 0.812f, 0.845f),
          Color.hsl(208f, 0.775f, 0.769f),
          Color.hsl(206f, 0.819f, 0.653f),
          Color.hsl(206f, 1.000f, 0.500f),
          Color.hsl(208f, 1.000f, 0.473f),
          Color.hsl(211f, 1.000f, 0.432f),
          Color.hsl(211f, 1.000f, 0.150f),
      )
  /** [Radix Colors] Collection: blueA */
  val blueA =
      listOf(
          Color.hsl(210f, 1.000f, 0.510f, 0.016f),
          Color.hsl(210f, 1.000f, 0.510f, 0.040f),
          Color.hsl(210f, 1.000f, 0.503f, 0.071f),
          Color.hsl(210f, 1.000f, 0.501f, 0.118f),
          Color.hsl(208f, 0.991f, 0.471f, 0.189f),
          Color.hsl(209f, 0.995f, 0.453f, 0.283f),
          Color.hsl(208f, 0.999f, 0.438f, 0.412f),
          Color.hsl(206f, 0.998f, 0.451f, 0.632f),
          Color.hsl(206f, 1.000f, 0.500f, 0.980f),
          Color.hsl(208f, 1.000f, 0.472f, 0.980f),
          Color.hsl(212f, 1.000f, 0.430f, 0.980f),
          Color.hsl(213f, 1.000f, 0.144f, 0.980f),
      )
  /** [Radix Colors] Collection: blueDark */
  val blueDark =
      listOf(
          Color.hsl(212f, 0.350f, 0.092f),
          Color.hsl(216f, 0.500f, 0.118f),
          Color.hsl(214f, 0.594f, 0.153f),
          Color.hsl(214f, 0.658f, 0.179f),
          Color.hsl(213f, 0.712f, 0.202f),
          Color.hsl(212f, 0.774f, 0.231f),
          Color.hsl(211f, 0.851f, 0.274f),
          Color.hsl(211f, 0.897f, 0.341f),
          Color.hsl(206f, 1.000f, 0.500f),
          Color.hsl(209f, 1.000f, 0.606f),
          Color.hsl(210f, 1.000f, 0.661f),
          Color.hsl(206f, 0.980f, 0.958f),
      )
  /** [Radix Colors] Collection: blueDarkA */
  val blueDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(221f, 0.978f, 0.524f, 0.059f),
          Color.hsl(215f, 0.993f, 0.542f, 0.135f),
          Color.hsl(215f, 0.993f, 0.538f, 0.198f),
          Color.hsl(213f, 0.994f, 0.528f, 0.252f),
          Color.hsl(212f, 0.999f, 0.517f, 0.323f),
          Color.hsl(211f, 1.000f, 0.507f, 0.435f),
          Color.hsl(211f, 0.998f, 0.509f, 0.597f),
          Color.hsl(205f, 1.000f, 0.500f, 0.980f),
          Color.hsl(208f, 1.000f, 0.607f, 0.980f),
          Color.hsl(209f, 1.000f, 0.663f, 0.980f),
          Color.hsl(196f, 1.000f, 0.968f, 0.980f),
      )
  /** [Radix Colors] Collection: bronze */
  val bronze =
      listOf(
          Color.hsl(15f, 0.300f, 0.991f),
          Color.hsl(17f, 0.636f, 0.978f),
          Color.hsl(17f, 0.421f, 0.952f),
          Color.hsl(17f, 0.352f, 0.921f),
          Color.hsl(17f, 0.315f, 0.882f),
          Color.hsl(17f, 0.290f, 0.830f),
          Color.hsl(17f, 0.269f, 0.756f),
          Color.hsl(17f, 0.251f, 0.665f),
          Color.hsl(17f, 0.200f, 0.540f),
          Color.hsl(17f, 0.181f, 0.501f),
          Color.hsl(15f, 0.200f, 0.431f),
          Color.hsl(12f, 0.220f, 0.215f),
      )
  /** [Radix Colors] Collection: bronzeA */
  val bronzeA =
      listOf(
          Color.hsl(0f, 0.893f, 0.183f, 0.012f),
          Color.hsl(17f, 0.951f, 0.401f, 0.036f),
          Color.hsl(18f, 0.983f, 0.298f, 0.067f),
          Color.hsl(17f, 0.996f, 0.260f, 0.106f),
          Color.hsl(19f, 0.996f, 0.238f, 0.157f),
          Color.hsl(17f, 0.992f, 0.225f, 0.220f),
          Color.hsl(18f, 0.997f, 0.216f, 0.310f),
          Color.hsl(17f, 0.995f, 0.202f, 0.420f),
          Color.hsl(18f, 0.999f, 0.167f, 0.553f),
          Color.hsl(17f, 0.992f, 0.154f, 0.589f),
          Color.hsl(15f, 0.999f, 0.132f, 0.655f),
          Color.hsl(12f, 0.987f, 0.057f, 0.832f),
      )
  /** [Radix Colors] Collection: bronzeDark */
  val bronzeDark =
      listOf(
          Color.hsl(17f, 0.100f, 0.088f),
          Color.hsl(15f, 0.148f, 0.106f),
          Color.hsl(15f, 0.163f, 0.143f),
          Color.hsl(16f, 0.171f, 0.172f),
          Color.hsl(16f, 0.176f, 0.196f),
          Color.hsl(16f, 0.181f, 0.229f),
          Color.hsl(17f, 0.188f, 0.288f),
          Color.hsl(17f, 0.196f, 0.380f),
          Color.hsl(17f, 0.200f, 0.540f),
          Color.hsl(18f, 0.240f, 0.590f),
          Color.hsl(18f, 0.350f, 0.685f),
          Color.hsl(18f, 0.570f, 0.941f),
      )
  /** [Radix Colors] Collection: bronzeDarkA */
  val bronzeDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(20f, 0.882f, 0.742f, 0.027f),
          Color.hsl(10f, 0.994f, 0.830f, 0.074f),
          Color.hsl(18f, 0.960f, 0.811f, 0.114f),
          Color.hsl(18f, 0.994f, 0.817f, 0.148f),
          Color.hsl(15f, 0.981f, 0.824f, 0.192f),
          Color.hsl(16f, 0.992f, 0.829f, 0.270f),
          Color.hsl(18f, 0.995f, 0.826f, 0.396f),
          Color.hsl(18f, 0.993f, 0.850f, 0.592f),
          Color.hsl(18f, 0.996f, 0.852f, 0.657f),
          Color.hsl(17f, 0.999f, 0.861f, 0.774f),
          Color.hsl(20f, 0.998f, 0.964f, 0.974f),
      )
  /** [Radix Colors] Collection: brown */
  val brown =
      listOf(
          Color.hsl(30f, 0.400f, 0.991f),
          Color.hsl(30f, 0.500f, 0.976f),
          Color.hsl(30f, 0.525f, 0.946f),
          Color.hsl(30f, 0.530f, 0.912f),
          Color.hsl(29f, 0.529f, 0.868f),
          Color.hsl(29f, 0.525f, 0.809f),
          Color.hsl(29f, 0.515f, 0.728f),
          Color.hsl(28f, 0.500f, 0.631f),
          Color.hsl(28f, 0.340f, 0.510f),
          Color.hsl(27f, 0.318f, 0.476f),
          Color.hsl(25f, 0.300f, 0.410f),
          Color.hsl(20f, 0.300f, 0.190f),
      )
  /** [Radix Colors] Collection: brownA */
  val brownA =
      listOf(
          Color.hsl(30f, 0.943f, 0.346f, 0.012f),
          Color.hsl(30f, 0.943f, 0.346f, 0.036f),
          Color.hsl(30f, 0.977f, 0.339f, 0.083f),
          Color.hsl(31f, 0.985f, 0.342f, 0.134f),
          Color.hsl(29f, 1.000f, 0.343f, 0.200f),
          Color.hsl(28f, 0.992f, 0.346f, 0.291f),
          Color.hsl(29f, 0.998f, 0.338f, 0.412f),
          Color.hsl(28f, 1.000f, 0.333f, 0.553f),
          Color.hsl(28f, 0.999f, 0.255f, 0.655f),
          Color.hsl(27f, 0.997f, 0.224f, 0.675f),
          Color.hsl(25f, 0.998f, 0.173f, 0.714f),
          Color.hsl(21f, 0.994f, 0.066f, 0.867f),
      )
  /** [Radix Colors] Collection: brownDark */
  val brownDark =
      listOf(
          Color.hsl(22f, 0.150f, 0.087f),
          Color.hsl(20f, 0.283f, 0.104f),
          Color.hsl(20f, 0.280f, 0.140f),
          Color.hsl(21f, 0.284f, 0.165f),
          Color.hsl(22f, 0.287f, 0.189f),
          Color.hsl(23f, 0.290f, 0.223f),
          Color.hsl(25f, 0.295f, 0.278f),
          Color.hsl(27f, 0.301f, 0.359f),
          Color.hsl(28f, 0.340f, 0.510f),
          Color.hsl(28f, 0.414f, 0.558f),
          Color.hsl(28f, 0.600f, 0.645f),
          Color.hsl(30f, 0.670f, 0.940f),
      )
  /** [Radix Colors] Collection: brownDarkA */
  val brownDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(22f, 0.996f, 0.536f, 0.035f),
          Color.hsl(18f, 0.978f, 0.690f, 0.088f),
          Color.hsl(21f, 0.982f, 0.710f, 0.123f),
          Color.hsl(25f, 0.984f, 0.721f, 0.158f),
          Color.hsl(25f, 0.987f, 0.735f, 0.206f),
          Color.hsl(25f, 0.990f, 0.746f, 0.289f),
          Color.hsl(28f, 0.992f, 0.753f, 0.407f),
          Color.hsl(28f, 1.000f, 0.748f, 0.642f),
          Color.hsl(28f, 0.999f, 0.749f, 0.712f),
          Color.hsl(28f, 0.999f, 0.749f, 0.843f),
          Color.hsl(32f, 0.982f, 0.957f, 0.979f),
      )
  /** [Radix Colors] Collection: crimson */
  val crimson =
      listOf(
          Color.hsl(332f, 1.000f, 0.994f),
          Color.hsl(330f, 1.000f, 0.984f),
          Color.hsl(331f, 0.856f, 0.966f),
          Color.hsl(331f, 0.781f, 0.942f),
          Color.hsl(332f, 0.721f, 0.911f),
          Color.hsl(333f, 0.670f, 0.867f),
          Color.hsl(335f, 0.635f, 0.804f),
          Color.hsl(336f, 0.623f, 0.729f),
          Color.hsl(336f, 0.800f, 0.578f),
          Color.hsl(336f, 0.737f, 0.535f),
          Color.hsl(336f, 0.750f, 0.472f),
          Color.hsl(340f, 0.650f, 0.145f),
      )
  /** [Radix Colors] Collection: crimsonA */
  val crimsonA =
      listOf(
          Color.hsl(340f, 1.000f, 0.510f, 0.012f),
          Color.hsl(330f, 1.000f, 0.510f, 0.032f),
          Color.hsl(332f, 0.991f, 0.471f, 0.063f),
          Color.hsl(331f, 0.999f, 0.443f, 0.102f),
          Color.hsl(333f, 0.999f, 0.423f, 0.153f),
          Color.hsl(333f, 0.995f, 0.405f, 0.224f),
          Color.hsl(335f, 0.997f, 0.391f, 0.322f),
          Color.hsl(336f, 0.995f, 0.385f, 0.440f),
          Color.hsl(336f, 0.999f, 0.443f, 0.761f),
          Color.hsl(336f, 1.000f, 0.425f, 0.808f),
          Color.hsl(336f, 0.998f, 0.403f, 0.883f),
          Color.hsl(340f, 0.990f, 0.100f, 0.950f),
      )
  /** [Radix Colors] Collection: crimsonDark */
  val crimsonDark =
      listOf(
          Color.hsl(335f, 0.200f, 0.096f),
          Color.hsl(335f, 0.322f, 0.116f),
          Color.hsl(335f, 0.425f, 0.165f),
          Color.hsl(335f, 0.472f, 0.193f),
          Color.hsl(335f, 0.509f, 0.218f),
          Color.hsl(335f, 0.557f, 0.253f),
          Color.hsl(336f, 0.629f, 0.308f),
          Color.hsl(336f, 0.749f, 0.390f),
          Color.hsl(336f, 0.800f, 0.578f),
          Color.hsl(339f, 0.841f, 0.626f),
          Color.hsl(341f, 0.900f, 0.673f),
          Color.hsl(332f, 0.870f, 0.960f),
      )
  /** [Radix Colors] Collection: crimsonDarkA */
  val crimsonDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(336f, 0.968f, 0.532f, 0.045f),
          Color.hsl(335f, 0.987f, 0.593f, 0.138f),
          Color.hsl(336f, 0.991f, 0.599f, 0.191f),
          Color.hsl(335f, 0.994f, 0.594f, 0.244f),
          Color.hsl(335f, 0.994f, 0.594f, 0.315f),
          Color.hsl(336f, 0.995f, 0.578f, 0.439f),
          Color.hsl(336f, 0.999f, 0.554f, 0.642f),
          Color.hsl(336f, 0.999f, 0.628f, 0.903f),
          Color.hsl(339f, 0.999f, 0.663f, 0.934f),
          Color.hsl(341f, 0.999f, 0.695f, 0.965f),
          Color.hsl(327f, 1.000f, 0.971f, 0.980f),
      )
  /** [Radix Colors] Collection: cyan */
  val cyan =
      listOf(
          Color.hsl(185f, 0.600f, 0.987f),
          Color.hsl(185f, 0.733f, 0.971f),
          Color.hsl(186f, 0.702f, 0.944f),
          Color.hsl(186f, 0.638f, 0.906f),
          Color.hsl(187f, 0.583f, 0.854f),
          Color.hsl(188f, 0.546f, 0.784f),
          Color.hsl(189f, 0.537f, 0.687f),
          Color.hsl(189f, 0.603f, 0.525f),
          Color.hsl(190f, 0.950f, 0.390f),
          Color.hsl(191f, 0.912f, 0.368f),
          Color.hsl(192f, 0.850f, 0.310f),
          Color.hsl(192f, 0.880f, 0.125f),
      )
  /** [Radix Colors] Collection: cyanA */
  val cyanA =
      listOf(
          Color.hsl(195f, 0.952f, 0.412f, 0.020f),
          Color.hsl(185f, 0.999f, 0.423f, 0.051f),
          Color.hsl(186f, 0.978f, 0.422f, 0.095f),
          Color.hsl(186f, 0.999f, 0.385f, 0.153f),
          Color.hsl(187f, 0.993f, 0.366f, 0.232f),
          Color.hsl(188f, 0.994f, 0.354f, 0.334f),
          Color.hsl(189f, 0.996f, 0.350f, 0.483f),
          Color.hsl(189f, 0.999f, 0.376f, 0.761f),
          Color.hsl(190f, 1.000f, 0.378f, 0.980f),
          Color.hsl(191f, 0.999f, 0.346f, 0.969f),
          Color.hsl(192f, 1.000f, 0.276f, 0.953f),
          Color.hsl(192f, 1.000f, 0.110f, 0.980f),
      )
  /** [Radix Colors] Collection: cyanDark */
  val cyanDark =
      listOf(
          Color.hsl(192f, 0.600f, 0.072f),
          Color.hsl(192f, 0.714f, 0.082f),
          Color.hsl(192f, 0.759f, 0.108f),
          Color.hsl(192f, 0.793f, 0.128f),
          Color.hsl(192f, 0.825f, 0.146f),
          Color.hsl(192f, 0.866f, 0.169f),
          Color.hsl(192f, 0.926f, 0.201f),
          Color.hsl(192f, 1.000f, 0.245f),
          Color.hsl(190f, 0.950f, 0.390f),
          Color.hsl(188f, 1.000f, 0.400f),
          Color.hsl(186f, 1.000f, 0.422f),
          Color.hsl(185f, 0.730f, 0.932f),
      )
  /** [Radix Colors] Collection: cyanDarkA */
  val cyanDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(196f, 1.000f, 0.500f, 0.031f),
          Color.hsl(192f, 0.980f, 0.509f, 0.085f),
          Color.hsl(194f, 0.996f, 0.513f, 0.133f),
          Color.hsl(192f, 0.995f, 0.513f, 0.173f),
          Color.hsl(193f, 0.997f, 0.504f, 0.226f),
          Color.hsl(192f, 1.000f, 0.500f, 0.310f),
          Color.hsl(193f, 1.000f, 0.500f, 0.425f),
          Color.hsl(190f, 0.998f, 0.508f, 0.731f),
          Color.hsl(188f, 1.000f, 0.500f, 0.775f),
          Color.hsl(186f, 1.000f, 0.499f, 0.824f),
          Color.hsl(185f, 0.998f, 0.951f, 0.978f),
      )
  /** [Radix Colors] Collection: gold */
  val gold =
      listOf(
          Color.hsl(50f, 0.200f, 0.991f),
          Color.hsl(47f, 0.529f, 0.967f),
          Color.hsl(46f, 0.382f, 0.937f),
          Color.hsl(44f, 0.327f, 0.901f),
          Color.hsl(43f, 0.299f, 0.857f),
          Color.hsl(41f, 0.283f, 0.798f),
          Color.hsl(39f, 0.276f, 0.719f),
          Color.hsl(36f, 0.272f, 0.618f),
          Color.hsl(36f, 0.200f, 0.495f),
          Color.hsl(36f, 0.198f, 0.457f),
          Color.hsl(36f, 0.200f, 0.390f),
          Color.hsl(36f, 0.160f, 0.200f),
      )
  /** [Radix Colors] Collection: goldA */
  val goldA =
      listOf(
          Color.hsl(60f, 0.893f, 0.183f, 0.012f),
          Color.hsl(47f, 0.999f, 0.346f, 0.051f),
          Color.hsl(45f, 0.970f, 0.279f, 0.087f),
          Color.hsl(46f, 0.980f, 0.254f, 0.134f),
          Color.hsl(43f, 0.984f, 0.226f, 0.185f),
          Color.hsl(41f, 0.997f, 0.220f, 0.259f),
          Color.hsl(38f, 0.998f, 0.215f, 0.357f),
          Color.hsl(36f, 0.993f, 0.215f, 0.487f),
          Color.hsl(36f, 0.999f, 0.162f, 0.604f),
          Color.hsl(36f, 0.992f, 0.146f, 0.636f),
          Color.hsl(35f, 0.991f, 0.112f, 0.687f),
          Color.hsl(38f, 0.980f, 0.038f, 0.832f),
      )
  /** [Radix Colors] Collection: goldDark */
  val goldDark =
      listOf(
          Color.hsl(44f, 0.090f, 0.083f),
          Color.hsl(43f, 0.143f, 0.096f),
          Color.hsl(42f, 0.155f, 0.130f),
          Color.hsl(41f, 0.164f, 0.156f),
          Color.hsl(41f, 0.169f, 0.178f),
          Color.hsl(40f, 0.176f, 0.208f),
          Color.hsl(38f, 0.185f, 0.264f),
          Color.hsl(36f, 0.196f, 0.351f),
          Color.hsl(36f, 0.200f, 0.495f),
          Color.hsl(36f, 0.223f, 0.545f),
          Color.hsl(35f, 0.300f, 0.640f),
          Color.hsl(49f, 0.520f, 0.938f),
      )
  /** [Radix Colors] Collection: goldDarkA */
  val goldDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(40f, 0.937f, 0.706f, 0.022f),
          Color.hsl(40f, 0.975f, 0.806f, 0.065f),
          Color.hsl(40f, 0.959f, 0.808f, 0.100f),
          Color.hsl(38f, 0.973f, 0.821f, 0.130f),
          Color.hsl(39f, 0.972f, 0.825f, 0.169f),
          Color.hsl(37f, 0.993f, 0.824f, 0.246f),
          Color.hsl(35f, 0.987f, 0.822f, 0.363f),
          Color.hsl(36f, 0.997f, 0.828f, 0.552f),
          Color.hsl(35f, 0.992f, 0.837f, 0.613f),
          Color.hsl(35f, 0.993f, 0.853f, 0.725f),
          Color.hsl(49f, 0.986f, 0.967f, 0.966f),
      )
  /** [Radix Colors] Collection: grass */
  val grass =
      listOf(
          Color.hsl(116f, 0.500f, 0.989f),
          Color.hsl(120f, 0.600f, 0.971f),
          Color.hsl(120f, 0.536f, 0.948f),
          Color.hsl(121f, 0.475f, 0.914f),
          Color.hsl(122f, 0.426f, 0.865f),
          Color.hsl(124f, 0.390f, 0.797f),
          Color.hsl(126f, 0.371f, 0.702f),
          Color.hsl(131f, 0.381f, 0.563f),
          Color.hsl(131f, 0.410f, 0.465f),
          Color.hsl(132f, 0.431f, 0.422f),
          Color.hsl(133f, 0.500f, 0.325f),
          Color.hsl(130f, 0.300f, 0.149f),
      )
  /** [Radix Colors] Collection: grassA */
  val grassA =
      listOf(
          Color.hsl(120f, 0.949f, 0.387f, 0.016f),
          Color.hsl(120f, 0.949f, 0.387f, 0.048f),
          Color.hsl(120f, 0.980f, 0.355f, 0.079f),
          Color.hsl(120f, 0.987f, 0.315f, 0.126f),
          Color.hsl(122f, 0.985f, 0.299f, 0.193f),
          Color.hsl(125f, 0.992f, 0.279f, 0.283f),
          Color.hsl(125f, 0.999f, 0.270f, 0.408f),
          Color.hsl(131f, 1.000f, 0.276f, 0.604f),
          Color.hsl(131f, 0.997f, 0.263f, 0.726f),
          Color.hsl(132f, 0.999f, 0.240f, 0.761f),
          Color.hsl(133f, 0.995f, 0.195f, 0.840f),
          Color.hsl(128f, 0.980f, 0.049f, 0.895f),
      )
  /** [Radix Colors] Collection: grassDark */
  val grassDark =
      listOf(
          Color.hsl(146f, 0.300f, 0.074f),
          Color.hsl(136f, 0.333f, 0.088f),
          Color.hsl(137f, 0.360f, 0.114f),
          Color.hsl(137f, 0.376f, 0.137f),
          Color.hsl(136f, 0.387f, 0.160f),
          Color.hsl(135f, 0.396f, 0.191f),
          Color.hsl(134f, 0.403f, 0.238f),
          Color.hsl(131f, 0.401f, 0.308f),
          Color.hsl(131f, 0.410f, 0.465f),
          Color.hsl(131f, 0.390f, 0.521f),
          Color.hsl(131f, 0.430f, 0.572f),
          Color.hsl(137f, 0.720f, 0.940f),
      )
  /** [Radix Colors] Collection: grassDarkA */
  val grassDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(107f, 0.972f, 0.619f, 0.022f),
          Color.hsl(128f, 0.965f, 0.698f, 0.066f),
          Color.hsl(130f, 1.000f, 0.702f, 0.100f),
          Color.hsl(130f, 0.982f, 0.691f, 0.140f),
          Color.hsl(132f, 0.999f, 0.693f, 0.187f),
          Color.hsl(132f, 0.999f, 0.698f, 0.261f),
          Color.hsl(130f, 0.996f, 0.705f, 0.370f),
          Color.hsl(130f, 0.997f, 0.706f, 0.618f),
          Color.hsl(131f, 1.000f, 0.735f, 0.674f),
          Color.hsl(130f, 0.997f, 0.756f, 0.731f),
          Color.hsl(137f, 1.000f, 0.958f, 0.980f),
      )
  /** [Radix Colors] Collection: gray */
  val gray =
      listOf(
          Color.hsl(0f, 0.000f, 0.990f),
          Color.hsl(0f, 0.000f, 0.973f),
          Color.hsl(0f, 0.000f, 0.951f),
          Color.hsl(0f, 0.000f, 0.930f),
          Color.hsl(0f, 0.000f, 0.909f),
          Color.hsl(0f, 0.000f, 0.887f),
          Color.hsl(0f, 0.000f, 0.858f),
          Color.hsl(0f, 0.000f, 0.780f),
          Color.hsl(0f, 0.000f, 0.561f),
          Color.hsl(0f, 0.000f, 0.523f),
          Color.hsl(0f, 0.000f, 0.435f),
          Color.hsl(0f, 0.000f, 0.090f),
      )
  /** [Radix Colors] Collection: grayA */
  val grayA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.012f),
          Color.hsl(0f, 0.000f, 0.000f, 0.027f),
          Color.hsl(0f, 0.000f, 0.000f, 0.047f),
          Color.hsl(0f, 0.000f, 0.000f, 0.071f),
          Color.hsl(0f, 0.000f, 0.000f, 0.090f),
          Color.hsl(0f, 0.000f, 0.000f, 0.114f),
          Color.hsl(0f, 0.000f, 0.000f, 0.141f),
          Color.hsl(0f, 0.000f, 0.000f, 0.220f),
          Color.hsl(0f, 0.000f, 0.000f, 0.439f),
          Color.hsl(0f, 0.000f, 0.000f, 0.478f),
          Color.hsl(0f, 0.000f, 0.000f, 0.565f),
          Color.hsl(0f, 0.000f, 0.000f, 0.910f),
      )
  /** [Radix Colors] Collection: grayDark */
  val grayDark =
      listOf(
          Color.hsl(0f, 0.000f, 0.085f),
          Color.hsl(0f, 0.000f, 0.110f),
          Color.hsl(0f, 0.000f, 0.136f),
          Color.hsl(0f, 0.000f, 0.158f),
          Color.hsl(0f, 0.000f, 0.179f),
          Color.hsl(0f, 0.000f, 0.205f),
          Color.hsl(0f, 0.000f, 0.243f),
          Color.hsl(0f, 0.000f, 0.312f),
          Color.hsl(0f, 0.000f, 0.439f),
          Color.hsl(0f, 0.000f, 0.494f),
          Color.hsl(0f, 0.000f, 0.628f),
          Color.hsl(0f, 0.000f, 0.930f),
      )
  /** [Radix Colors] Collection: grayDarkA */
  val grayDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 1.000f, 0.000f),
          Color.hsl(0f, 0.000f, 1.000f, 0.026f),
          Color.hsl(0f, 0.000f, 1.000f, 0.056f),
          Color.hsl(0f, 0.000f, 1.000f, 0.077f),
          Color.hsl(0f, 0.000f, 1.000f, 0.103f),
          Color.hsl(0f, 0.000f, 1.000f, 0.129f),
          Color.hsl(0f, 0.000f, 1.000f, 0.172f),
          Color.hsl(0f, 0.000f, 1.000f, 0.249f),
          Color.hsl(0f, 0.000f, 1.000f, 0.386f),
          Color.hsl(0f, 0.000f, 1.000f, 0.446f),
          Color.hsl(0f, 0.000f, 1.000f, 0.592f),
          Color.hsl(0f, 0.000f, 1.000f, 0.923f),
      )
  /** [Radix Colors] Collection: green */
  val green =
      listOf(
          Color.hsl(136f, 0.500f, 0.989f),
          Color.hsl(138f, 0.625f, 0.969f),
          Color.hsl(139f, 0.552f, 0.945f),
          Color.hsl(140f, 0.487f, 0.910f),
          Color.hsl(141f, 0.437f, 0.860f),
          Color.hsl(143f, 0.403f, 0.790f),
          Color.hsl(146f, 0.385f, 0.690f),
          Color.hsl(151f, 0.402f, 0.541f),
          Color.hsl(151f, 0.550f, 0.415f),
          Color.hsl(152f, 0.575f, 0.376f),
          Color.hsl(153f, 0.670f, 0.285f),
          Color.hsl(155f, 0.400f, 0.140f),
      )
  /** [Radix Colors] Collection: greenA */
  val greenA =
      listOf(
          Color.hsl(140f, 0.949f, 0.387f, 0.016f),
          Color.hsl(138f, 0.999f, 0.385f, 0.051f),
          Color.hsl(139f, 0.977f, 0.369f, 0.087f),
          Color.hsl(139f, 0.985f, 0.327f, 0.134f),
          Color.hsl(141f, 1.000f, 0.304f, 0.200f),
          Color.hsl(142f, 0.990f, 0.289f, 0.295f),
          Color.hsl(146f, 0.995f, 0.276f, 0.428f),
          Color.hsl(151f, 0.995f, 0.288f, 0.644f),
          Color.hsl(151f, 0.999f, 0.280f, 0.812f),
          Color.hsl(152f, 0.996f, 0.258f, 0.840f),
          Color.hsl(153f, 0.999f, 0.210f, 0.906f),
          Color.hsl(155f, 0.994f, 0.062f, 0.918f),
      )
  /** [Radix Colors] Collection: greenDark */
  val greenDark =
      listOf(
          Color.hsl(146f, 0.300f, 0.074f),
          Color.hsl(155f, 0.442f, 0.084f),
          Color.hsl(155f, 0.467f, 0.109f),
          Color.hsl(154f, 0.484f, 0.129f),
          Color.hsl(154f, 0.497f, 0.149f),
          Color.hsl(154f, 0.509f, 0.176f),
          Color.hsl(153f, 0.518f, 0.218f),
          Color.hsl(151f, 0.517f, 0.284f),
          Color.hsl(151f, 0.550f, 0.415f),
          Color.hsl(151f, 0.493f, 0.465f),
          Color.hsl(151f, 0.500f, 0.532f),
          Color.hsl(137f, 0.720f, 0.940f),
      )
  /** [Radix Colors] Collection: greenDarkA */
  val greenDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(169f, 1.000f, 0.485f, 0.027f),
          Color.hsl(162f, 0.987f, 0.579f, 0.070f),
          Color.hsl(158f, 0.986f, 0.597f, 0.105f),
          Color.hsl(158f, 0.986f, 0.607f, 0.140f),
          Color.hsl(156f, 0.999f, 0.620f, 0.187f),
          Color.hsl(154f, 0.995f, 0.631f, 0.257f),
          Color.hsl(152f, 0.997f, 0.642f, 0.370f),
          Color.hsl(151f, 0.997f, 0.638f, 0.605f),
          Color.hsl(152f, 0.999f, 0.665f, 0.661f),
          Color.hsl(151f, 0.997f, 0.692f, 0.740f),
          Color.hsl(137f, 1.000f, 0.958f, 0.980f),
      )
  /** [Radix Colors] Collection: indigo */
  val indigo =
      listOf(
          Color.hsl(225f, 0.600f, 0.994f),
          Color.hsl(223f, 1.000f, 0.986f),
          Color.hsl(223f, 0.984f, 0.971f),
          Color.hsl(223f, 0.929f, 0.950f),
          Color.hsl(224f, 0.871f, 0.920f),
          Color.hsl(224f, 0.819f, 0.878f),
          Color.hsl(225f, 0.774f, 0.821f),
          Color.hsl(226f, 0.754f, 0.745f),
          Color.hsl(226f, 0.700f, 0.555f),
          Color.hsl(226f, 0.586f, 0.513f),
          Color.hsl(226f, 0.550f, 0.450f),
          Color.hsl(226f, 0.620f, 0.170f),
      )
  /** [Radix Colors] Collection: indigoA */
  val indigoA =
      listOf(
          Color.hsl(240f, 0.926f, 0.265f, 0.008f),
          Color.hsl(223f, 1.000f, 0.510f, 0.028f),
          Color.hsl(224f, 1.000f, 0.501f, 0.059f),
          Color.hsl(223f, 0.980f, 0.485f, 0.099f),
          Color.hsl(225f, 0.986f, 0.464f, 0.150f),
          Color.hsl(224f, 0.995f, 0.449f, 0.224f),
          Color.hsl(225f, 0.997f, 0.439f, 0.318f),
          Color.hsl(226f, 0.995f, 0.431f, 0.448f),
          Color.hsl(226f, 1.000f, 0.412f, 0.757f),
          Color.hsl(226f, 0.998f, 0.371f, 0.773f),
          Color.hsl(226f, 0.996f, 0.311f, 0.797f),
          Color.hsl(226f, 0.993f, 0.114f, 0.938f),
      )
  /** [Radix Colors] Collection: indigoDark */
  val indigoDark =
      listOf(
          Color.hsl(229f, 0.240f, 0.100f),
          Color.hsl(230f, 0.364f, 0.129f),
          Color.hsl(228f, 0.433f, 0.175f),
          Color.hsl(227f, 0.472f, 0.210f),
          Color.hsl(227f, 0.500f, 0.241f),
          Color.hsl(226f, 0.529f, 0.282f),
          Color.hsl(226f, 0.560f, 0.345f),
          Color.hsl(226f, 0.582f, 0.441f),
          Color.hsl(226f, 0.700f, 0.555f),
          Color.hsl(227f, 0.752f, 0.616f),
          Color.hsl(228f, 1.000f, 0.759f),
          Color.hsl(226f, 0.830f, 0.963f),
      )
  /** [Radix Colors] Collection: indigoDarkA */
  val indigoDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(234f, 0.974f, 0.599f, 0.059f),
          Color.hsl(228f, 0.992f, 0.617f, 0.144f),
          Color.hsl(227f, 0.997f, 0.620f, 0.211f),
          Color.hsl(227f, 0.992f, 0.623f, 0.270f),
          Color.hsl(226f, 0.999f, 0.621f, 0.350f),
          Color.hsl(226f, 0.999f, 0.620f, 0.471f),
          Color.hsl(226f, 0.999f, 0.621f, 0.655f),
          Color.hsl(226f, 0.999f, 0.636f, 0.848f),
          Color.hsl(227f, 0.998f, 0.677f, 0.893f),
          Color.hsl(227f, 1.000f, 0.763f, 0.980f),
          Color.hsl(226f, 1.000f, 0.975f, 0.980f),
      )
  /** [Radix Colors] Collection: lime */
  val lime =
      listOf(
          Color.hsl(85f, 0.500f, 0.987f),
          Color.hsl(85f, 0.667f, 0.965f),
          Color.hsl(85f, 0.760f, 0.923f),
          Color.hsl(84f, 0.753f, 0.875f),
          Color.hsl(84f, 0.715f, 0.819f),
          Color.hsl(82f, 0.650f, 0.746f),
          Color.hsl(79f, 0.532f, 0.618f),
          Color.hsl(76f, 0.617f, 0.451f),
          Color.hsl(81f, 0.670f, 0.500f),
          Color.hsl(80f, 0.683f, 0.469f),
          Color.hsl(75f, 0.800f, 0.260f),
          Color.hsl(78f, 0.700f, 0.115f),
      )
  /** [Radix Colors] Collection: limeA */
  val limeA =
      listOf(
          Color.hsl(80f, 0.938f, 0.314f, 0.020f),
          Color.hsl(85f, 0.993f, 0.402f, 0.059f),
          Color.hsl(84f, 0.987f, 0.432f, 0.138f),
          Color.hsl(84f, 0.996f, 0.430f, 0.220f),
          Color.hsl(85f, 0.998f, 0.418f, 0.310f),
          Color.hsl(82f, 0.998f, 0.393f, 0.420f),
          Color.hsl(79f, 0.997f, 0.346f, 0.585f),
          Color.hsl(76f, 0.998f, 0.337f, 0.828f),
          Color.hsl(81f, 0.998f, 0.402f, 0.836f),
          Color.hsl(80f, 1.000f, 0.376f, 0.851f),
          Color.hsl(75f, 0.995f, 0.220f, 0.950f),
          Color.hsl(78f, 0.996f, 0.084f, 0.965f),
      )
  /** [Radix Colors] Collection: limeDark */
  val limeDark =
      listOf(
          Color.hsl(75f, 0.550f, 0.060f),
          Color.hsl(74f, 0.568f, 0.073f),
          Color.hsl(78f, 0.502f, 0.099f),
          Color.hsl(79f, 0.503f, 0.121f),
          Color.hsl(79f, 0.526f, 0.142f),
          Color.hsl(78f, 0.557f, 0.167f),
          Color.hsl(77f, 0.597f, 0.201f),
          Color.hsl(75f, 0.648f, 0.245f),
          Color.hsl(81f, 0.670f, 0.500f),
          Color.hsl(75f, 0.850f, 0.600f),
          Color.hsl(81f, 0.700f, 0.438f),
          Color.hsl(84f, 0.790f, 0.926f),
      )
  /** [Radix Colors] Collection: limeDarkA */
  val limeDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(75f, 0.964f, 0.596f, 0.022f),
          Color.hsl(88f, 0.980f, 0.704f, 0.061f),
          Color.hsl(81f, 0.978f, 0.674f, 0.096f),
          Color.hsl(82f, 0.984f, 0.656f, 0.135f),
          Color.hsl(79f, 0.997f, 0.643f, 0.182f),
          Color.hsl(77f, 0.991f, 0.621f, 0.252f),
          Color.hsl(75f, 1.000f, 0.600f, 0.342f),
          Color.hsl(81f, 0.998f, 0.597f, 0.819f),
          Color.hsl(75f, 0.998f, 0.637f, 0.936f),
          Color.hsl(81f, 0.999f, 0.587f, 0.719f),
          Color.hsl(83f, 1.000f, 0.942f, 0.980f),
      )
  /** [Radix Colors] Collection: mauve */
  val mauve =
      listOf(
          Color.hsl(300f, 0.200f, 0.990f),
          Color.hsl(300f, 0.077f, 0.975f),
          Color.hsl(294f, 0.055f, 0.953f),
          Color.hsl(289f, 0.047f, 0.933f),
          Color.hsl(283f, 0.044f, 0.913f),
          Color.hsl(278f, 0.041f, 0.891f),
          Color.hsl(271f, 0.039f, 0.863f),
          Color.hsl(255f, 0.037f, 0.788f),
          Color.hsl(252f, 0.040f, 0.573f),
          Color.hsl(253f, 0.035f, 0.535f),
          Color.hsl(252f, 0.040f, 0.448f),
          Color.hsl(260f, 0.250f, 0.110f),
      )
  /** [Radix Colors] Collection: mauveA */
  val mauveA =
      listOf(
          Color.hsl(300f, 0.893f, 0.183f, 0.012f),
          Color.hsl(300f, 0.781f, 0.090f, 0.028f),
          Color.hsl(300f, 0.995f, 0.077f, 0.051f),
          Color.hsl(270f, 0.905f, 0.061f, 0.071f),
          Color.hsl(270f, 0.830f, 0.052f, 0.091f),
          Color.hsl(300f, 0.935f, 0.037f, 0.114f),
          Color.hsl(270f, 0.826f, 0.033f, 0.142f),
          Color.hsl(255f, 0.952f, 0.037f, 0.220f),
          Color.hsl(255f, 0.948f, 0.037f, 0.444f),
          Color.hsl(253f, 0.965f, 0.038f, 0.483f),
          Color.hsl(247f, 0.979f, 0.032f, 0.569f),
          Color.hsl(261f, 0.987f, 0.030f, 0.918f),
      )
  /** [Radix Colors] Collection: mauveDark */
  val mauveDark =
      listOf(
          Color.hsl(246f, 0.060f, 0.090f),
          Color.hsl(240f, 0.051f, 0.116f),
          Color.hsl(241f, 0.050f, 0.143f),
          Color.hsl(242f, 0.049f, 0.165f),
          Color.hsl(243f, 0.049f, 0.188f),
          Color.hsl(244f, 0.049f, 0.215f),
          Color.hsl(245f, 0.049f, 0.254f),
          Color.hsl(247f, 0.048f, 0.325f),
          Color.hsl(252f, 0.040f, 0.452f),
          Color.hsl(247f, 0.034f, 0.507f),
          Color.hsl(253f, 0.040f, 0.637f),
          Color.hsl(256f, 0.060f, 0.932f),
      )
  /** [Radix Colors] Collection: mauveDarkA */
  val mauveDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(240f, 0.767f, 0.912f, 0.031f),
          Color.hsl(240f, 0.860f, 0.958f, 0.061f),
          Color.hsl(240f, 0.918f, 0.947f, 0.087f),
          Color.hsl(240f, 0.915f, 0.958f, 0.113f),
          Color.hsl(240f, 0.920f, 0.938f, 0.148f),
          Color.hsl(240f, 0.948f, 0.953f, 0.191f),
          Color.hsl(249f, 0.981f, 0.952f, 0.273f),
          Color.hsl(248f, 0.976f, 0.962f, 0.416f),
          Color.hsl(248f, 0.955f, 0.966f, 0.477f),
          Color.hsl(250f, 0.980f, 0.980f, 0.615f),
          Color.hsl(240f, 0.939f, 0.996f, 0.931f),
      )
  /** [Radix Colors] Collection: mint */
  val mint =
      listOf(
          Color.hsl(165f, 0.800f, 0.988f),
          Color.hsl(164f, 0.882f, 0.967f),
          Color.hsl(164f, 0.766f, 0.933f),
          Color.hsl(165f, 0.688f, 0.895f),
          Color.hsl(165f, 0.606f, 0.845f),
          Color.hsl(165f, 0.535f, 0.769f),
          Color.hsl(166f, 0.507f, 0.661f),
          Color.hsl(168f, 0.528f, 0.510f),
          Color.hsl(167f, 0.650f, 0.660f),
          Color.hsl(167f, 0.593f, 0.631f),
          Color.hsl(172f, 0.720f, 0.285f),
          Color.hsl(172f, 0.700f, 0.120f),
      )
  /** [Radix Colors] Collection: mintA */
  val mintA =
      listOf(
          Color.hsl(168f, 0.954f, 0.428f, 0.024f),
          Color.hsl(164f, 0.991f, 0.471f, 0.063f),
          Color.hsl(164f, 0.993f, 0.435f, 0.118f),
          Color.hsl(164f, 0.993f, 0.413f, 0.177f),
          Color.hsl(165f, 0.990f, 0.375f, 0.248f),
          Color.hsl(165f, 1.000f, 0.350f, 0.353f),
          Color.hsl(166f, 0.999f, 0.335f, 0.510f),
          Color.hsl(168f, 0.996f, 0.346f, 0.750f),
          Color.hsl(167f, 0.999f, 0.395f, 0.561f),
          Color.hsl(167f, 0.997f, 0.374f, 0.589f),
          Color.hsl(172f, 0.998f, 0.224f, 0.922f),
          Color.hsl(172f, 0.997f, 0.088f, 0.965f),
      )
  /** [Radix Colors] Collection: mintDark */
  val mintDark =
      listOf(
          Color.hsl(173f, 0.500f, 0.066f),
          Color.hsl(176f, 0.730f, 0.073f),
          Color.hsl(175f, 0.793f, 0.089f),
          Color.hsl(174f, 0.848f, 0.103f),
          Color.hsl(174f, 0.902f, 0.119f),
          Color.hsl(173f, 0.960f, 0.138f),
          Color.hsl(172f, 1.000f, 0.168f),
          Color.hsl(170f, 1.000f, 0.214f),
          Color.hsl(167f, 0.650f, 0.660f),
          Color.hsl(163f, 0.800f, 0.770f),
          Color.hsl(167f, 0.700f, 0.480f),
          Color.hsl(165f, 0.800f, 0.948f),
      )
  /** [Radix Colors] Collection: mintDarkA */
  val mintDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(180f, 1.000f, 0.492f, 0.031f),
          Color.hsl(176f, 1.000f, 0.497f, 0.070f),
          Color.hsl(173f, 1.000f, 0.497f, 0.105f),
          Color.hsl(173f, 1.000f, 0.498f, 0.144f),
          Color.hsl(172f, 1.000f, 0.498f, 0.192f),
          Color.hsl(171f, 1.000f, 0.499f, 0.266f),
          Color.hsl(169f, 1.000f, 0.499f, 0.366f),
          Color.hsl(167f, 0.998f, 0.750f, 0.870f),
          Color.hsl(163f, 0.999f, 0.807f, 0.948f),
          Color.hsl(167f, 0.999f, 0.587f, 0.796f),
          Color.hsl(169f, 1.000f, 0.962f, 0.980f),
      )
  /** [Radix Colors] Collection: olive */
  val olive =
      listOf(
          Color.hsl(110f, 0.200f, 0.990f),
          Color.hsl(120f, 0.167f, 0.976f),
          Color.hsl(119f, 0.101f, 0.952f),
          Color.hsl(118f, 0.081f, 0.930f),
          Color.hsl(117f, 0.071f, 0.908f),
          Color.hsl(115f, 0.064f, 0.885f),
          Color.hsl(114f, 0.059f, 0.854f),
          Color.hsl(110f, 0.052f, 0.773f),
          Color.hsl(110f, 0.035f, 0.555f),
          Color.hsl(111f, 0.028f, 0.517f),
          Color.hsl(110f, 0.030f, 0.430f),
          Color.hsl(110f, 0.250f, 0.095f),
      )
  /** [Radix Colors] Collection: oliveA */
  val oliveA =
      listOf(
          Color.hsl(120f, 0.893f, 0.183f, 0.012f),
          Color.hsl(120f, 0.877f, 0.160f, 0.028f),
          Color.hsl(120f, 0.995f, 0.077f, 0.051f),
          Color.hsl(120f, 0.923f, 0.085f, 0.075f),
          Color.hsl(120f, 0.860f, 0.069f, 0.099f),
          Color.hsl(120f, 0.948f, 0.068f, 0.122f),
          Color.hsl(120f, 0.993f, 0.052f, 0.153f),
          Color.hsl(110f, 0.938f, 0.052f, 0.240f),
          Color.hsl(111f, 0.987f, 0.030f, 0.459f),
          Color.hsl(111f, 0.935f, 0.029f, 0.499f),
          Color.hsl(111f, 0.952f, 0.025f, 0.585f),
          Color.hsl(110f, 0.976f, 0.026f, 0.930f),
      )
  /** [Radix Colors] Collection: oliveDark */
  val oliveDark =
      listOf(
          Color.hsl(110f, 0.050f, 0.086f),
          Color.hsl(105f, 0.074f, 0.106f),
          Color.hsl(106f, 0.064f, 0.131f),
          Color.hsl(106f, 0.058f, 0.153f),
          Color.hsl(107f, 0.053f, 0.174f),
          Color.hsl(107f, 0.049f, 0.199f),
          Color.hsl(108f, 0.044f, 0.236f),
          Color.hsl(110f, 0.038f, 0.306f),
          Color.hsl(110f, 0.060f, 0.425f),
          Color.hsl(111f, 0.048f, 0.482f),
          Color.hsl(110f, 0.050f, 0.618f),
          Color.hsl(110f, 0.060f, 0.930f),
      )
  /** [Radix Colors] Collection: oliveDarkA */
  val oliveDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(91f, 0.970f, 0.840f, 0.026f),
          Color.hsl(101f, 0.874f, 0.877f, 0.057f),
          Color.hsl(92f, 0.918f, 0.941f, 0.078f),
          Color.hsl(101f, 0.926f, 0.935f, 0.104f),
          Color.hsl(102f, 0.911f, 0.946f, 0.130f),
          Color.hsl(102f, 0.925f, 0.959f, 0.173f),
          Color.hsl(107f, 1.000f, 0.965f, 0.250f),
          Color.hsl(110f, 0.983f, 0.941f, 0.397f),
          Color.hsl(109f, 0.996f, 0.953f, 0.457f),
          Color.hsl(113f, 0.953f, 0.972f, 0.600f),
          Color.hsl(120f, 0.935f, 0.996f, 0.927f),
      )
  /** [Radix Colors] Collection: orange */
  val orange =
      listOf(
          Color.hsl(24f, 0.700f, 0.990f),
          Color.hsl(24f, 0.833f, 0.976f),
          Color.hsl(24f, 1.000f, 0.953f),
          Color.hsl(25f, 1.000f, 0.922f),
          Color.hsl(25f, 1.000f, 0.882f),
          Color.hsl(25f, 1.000f, 0.828f),
          Color.hsl(24f, 1.000f, 0.753f),
          Color.hsl(24f, 0.945f, 0.643f),
          Color.hsl(24f, 0.940f, 0.500f),
          Color.hsl(24f, 1.000f, 0.465f),
          Color.hsl(24f, 1.000f, 0.370f),
          Color.hsl(15f, 0.600f, 0.170f),
      )
  /** [Radix Colors] Collection: orangeA */
  val orangeA =
      listOf(
          Color.hsl(20f, 0.949f, 0.387f, 0.016f),
          Color.hsl(24f, 0.958f, 0.465f, 0.044f),
          Color.hsl(25f, 1.000f, 0.505f, 0.095f),
          Color.hsl(26f, 1.000f, 0.500f, 0.157f),
          Color.hsl(25f, 1.000f, 0.501f, 0.236f),
          Color.hsl(25f, 1.000f, 0.501f, 0.346f),
          Color.hsl(24f, 1.000f, 0.501f, 0.495f),
          Color.hsl(24f, 0.997f, 0.487f, 0.695f),
          Color.hsl(24f, 0.999f, 0.484f, 0.969f),
          Color.hsl(23f, 1.000f, 0.464f, 0.980f),
          Color.hsl(23f, 1.000f, 0.368f, 0.980f),
          Color.hsl(15f, 0.994f, 0.110f, 0.934f),
      )
  /** [Radix Colors] Collection: orangeDark */
  val orangeDark =
      listOf(
          Color.hsl(30f, 0.700f, 0.072f),
          Color.hsl(28f, 1.000f, 0.084f),
          Color.hsl(26f, 0.911f, 0.116f),
          Color.hsl(25f, 0.883f, 0.141f),
          Color.hsl(24f, 0.876f, 0.166f),
          Color.hsl(24f, 0.886f, 0.198f),
          Color.hsl(24f, 0.924f, 0.240f),
          Color.hsl(25f, 1.000f, 0.290f),
          Color.hsl(24f, 0.940f, 0.500f),
          Color.hsl(24f, 1.000f, 0.585f),
          Color.hsl(24f, 1.000f, 0.622f),
          Color.hsl(24f, 0.970f, 0.932f),
      )
  /** [Radix Colors] Collection: orangeDarkA */
  val orangeDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(13f, 1.000f, 0.497f, 0.054f),
          Color.hsl(20f, 1.000f, 0.497f, 0.117f),
          Color.hsl(23f, 1.000f, 0.498f, 0.166f),
          Color.hsl(23f, 0.994f, 0.501f, 0.215f),
          Color.hsl(23f, 0.998f, 0.511f, 0.286f),
          Color.hsl(23f, 0.997f, 0.506f, 0.389f),
          Color.hsl(24f, 1.000f, 0.499f, 0.523f),
          Color.hsl(24f, 0.999f, 0.516f, 0.965f),
          Color.hsl(25f, 1.000f, 0.586f, 0.980f),
          Color.hsl(24f, 1.000f, 0.624f, 0.980f),
          Color.hsl(26f, 1.000f, 0.942f, 0.980f),
      )
  /** [Radix Colors] Collection: pink */
  val pink =
      listOf(
          Color.hsl(322f, 1.000f, 0.994f),
          Color.hsl(323f, 1.000f, 0.984f),
          Color.hsl(323f, 0.863f, 0.965f),
          Color.hsl(323f, 0.787f, 0.942f),
          Color.hsl(323f, 0.722f, 0.911f),
          Color.hsl(323f, 0.663f, 0.866f),
          Color.hsl(323f, 0.620f, 0.801f),
          Color.hsl(323f, 0.603f, 0.724f),
          Color.hsl(322f, 0.650f, 0.545f),
          Color.hsl(322f, 0.639f, 0.507f),
          Color.hsl(322f, 0.750f, 0.460f),
          Color.hsl(320f, 0.700f, 0.135f),
      )
  /** [Radix Colors] Collection: pinkA */
  val pinkA =
      listOf(
          Color.hsl(320f, 1.000f, 0.510f, 0.012f),
          Color.hsl(323f, 1.000f, 0.510f, 0.032f),
          Color.hsl(323f, 0.989f, 0.473f, 0.067f),
          Color.hsl(323f, 0.999f, 0.443f, 0.102f),
          Color.hsl(324f, 0.999f, 0.423f, 0.153f),
          Color.hsl(323f, 0.995f, 0.396f, 0.224f),
          Color.hsl(323f, 0.997f, 0.385f, 0.322f),
          Color.hsl(323f, 0.995f, 0.377f, 0.444f),
          Color.hsl(322f, 0.997f, 0.393f, 0.750f),
          Color.hsl(322f, 1.000f, 0.391f, 0.808f),
          Color.hsl(322f, 0.998f, 0.390f, 0.887f),
          Color.hsl(321f, 0.998f, 0.100f, 0.961f),
      )
  /** [Radix Colors] Collection: pinkDark */
  val pinkDark =
      listOf(
          Color.hsl(318f, 0.250f, 0.096f),
          Color.hsl(319f, 0.322f, 0.116f),
          Color.hsl(319f, 0.410f, 0.160f),
          Color.hsl(320f, 0.454f, 0.187f),
          Color.hsl(320f, 0.490f, 0.211f),
          Color.hsl(321f, 0.536f, 0.244f),
          Color.hsl(321f, 0.611f, 0.297f),
          Color.hsl(322f, 0.749f, 0.375f),
          Color.hsl(322f, 0.650f, 0.545f),
          Color.hsl(323f, 0.728f, 0.592f),
          Color.hsl(325f, 0.900f, 0.664f),
          Color.hsl(322f, 0.900f, 0.958f),
      )
  /** [Radix Colors] Collection: pinkDarkA */
  val pinkDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(320f, 0.981f, 0.641f, 0.036f),
          Color.hsl(320f, 0.991f, 0.631f, 0.121f),
          Color.hsl(320f, 0.995f, 0.627f, 0.170f),
          Color.hsl(319f, 0.997f, 0.615f, 0.219f),
          Color.hsl(322f, 0.994f, 0.608f, 0.291f),
          Color.hsl(321f, 0.996f, 0.587f, 0.407f),
          Color.hsl(322f, 0.997f, 0.554f, 0.608f),
          Color.hsl(322f, 1.000f, 0.646f, 0.817f),
          Color.hsl(323f, 1.000f, 0.663f, 0.875f),
          Color.hsl(325f, 0.999f, 0.686f, 0.960f),
          Color.hsl(314f, 1.000f, 0.969f, 0.980f),
      )
  /** [Radix Colors] Collection: plum */
  val plum =
      listOf(
          Color.hsl(292f, 0.900f, 0.994f),
          Color.hsl(300f, 1.000f, 0.986f),
          Color.hsl(299f, 0.712f, 0.964f),
          Color.hsl(299f, 0.620f, 0.938f),
          Color.hsl(298f, 0.561f, 0.905f),
          Color.hsl(296f, 0.513f, 0.858f),
          Color.hsl(295f, 0.482f, 0.789f),
          Color.hsl(292f, 0.477f, 0.708f),
          Color.hsl(292f, 0.450f, 0.510f),
          Color.hsl(292f, 0.502f, 0.469f),
          Color.hsl(292f, 0.600f, 0.425f),
          Color.hsl(291f, 0.660f, 0.140f),
      )
  /** [Radix Colors] Collection: plumA */
  val plumA =
      listOf(
          Color.hsl(280f, 1.000f, 0.510f, 0.012f),
          Color.hsl(300f, 1.000f, 0.510f, 0.028f),
          Color.hsl(300f, 0.990f, 0.409f, 0.063f),
          Color.hsl(300f, 0.999f, 0.385f, 0.102f),
          Color.hsl(298f, 0.982f, 0.359f, 0.150f),
          Color.hsl(297f, 0.996f, 0.337f, 0.216f),
          Color.hsl(295f, 0.997f, 0.326f, 0.314f),
          Color.hsl(292f, 0.996f, 0.324f, 0.432f),
          Color.hsl(292f, 0.999f, 0.310f, 0.710f),
          Color.hsl(292f, 0.999f, 0.308f, 0.765f),
          Color.hsl(292f, 0.998f, 0.307f, 0.832f),
          Color.hsl(291f, 0.999f, 0.097f, 0.953f),
      )
  /** [Radix Colors] Collection: plumDark */
  val plumDark =
      listOf(
          Color.hsl(301f, 0.200f, 0.094f),
          Color.hsl(300f, 0.298f, 0.112f),
          Color.hsl(298f, 0.344f, 0.153f),
          Color.hsl(297f, 0.368f, 0.183f),
          Color.hsl(296f, 0.385f, 0.211f),
          Color.hsl(295f, 0.404f, 0.247f),
          Color.hsl(294f, 0.427f, 0.306f),
          Color.hsl(292f, 0.451f, 0.400f),
          Color.hsl(292f, 0.450f, 0.510f),
          Color.hsl(295f, 0.500f, 0.554f),
          Color.hsl(300f, 0.600f, 0.620f),
          Color.hsl(296f, 0.740f, 0.957f),
      )
  /** [Radix Colors] Collection: plumDarkA */
  val plumDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(300f, 0.964f, 0.584f, 0.036f),
          Color.hsl(300f, 0.994f, 0.671f, 0.102f),
          Color.hsl(295f, 0.998f, 0.663f, 0.155f),
          Color.hsl(295f, 0.994f, 0.671f, 0.204f),
          Color.hsl(294f, 0.990f, 0.678f, 0.262f),
          Color.hsl(294f, 0.999f, 0.677f, 0.363f),
          Color.hsl(292f, 0.998f, 0.675f, 0.527f),
          Color.hsl(292f, 0.999f, 0.692f, 0.695f),
          Color.hsl(295f, 0.999f, 0.708f, 0.748f),
          Color.hsl(300f, 0.998f, 0.729f, 0.828f),
          Color.hsl(300f, 1.000f, 0.971f, 0.980f),
      )
  /** [Radix Colors] Collection: purple */
  val purple =
      listOf(
          Color.hsl(280f, 0.650f, 0.994f),
          Color.hsl(276f, 1.000f, 0.990f),
          Color.hsl(276f, 0.831f, 0.970f),
          Color.hsl(275f, 0.764f, 0.947f),
          Color.hsl(275f, 0.708f, 0.918f),
          Color.hsl(274f, 0.654f, 0.878f),
          Color.hsl(273f, 0.610f, 0.817f),
          Color.hsl(272f, 0.600f, 0.735f),
          Color.hsl(272f, 0.510f, 0.540f),
          Color.hsl(272f, 0.468f, 0.503f),
          Color.hsl(272f, 0.500f, 0.458f),
          Color.hsl(272f, 0.660f, 0.160f),
      )
  /** [Radix Colors] Collection: purpleA */
  val purpleA =
      listOf(
          Color.hsl(300f, 0.943f, 0.346f, 0.012f),
          Color.hsl(276f, 1.000f, 0.510f, 0.020f),
          Color.hsl(277f, 0.996f, 0.465f, 0.055f),
          Color.hsl(274f, 0.979f, 0.443f, 0.095f),
          Color.hsl(276f, 0.986f, 0.420f, 0.142f),
          Color.hsl(275f, 1.000f, 0.392f, 0.200f),
          Color.hsl(273f, 0.992f, 0.382f, 0.295f),
          Color.hsl(272f, 0.997f, 0.376f, 0.424f),
          Color.hsl(272f, 0.996f, 0.340f, 0.695f),
          Color.hsl(272f, 0.997f, 0.320f, 0.730f),
          Color.hsl(272f, 0.998f, 0.297f, 0.773f),
          Color.hsl(272f, 0.992f, 0.113f, 0.946f),
      )
  /** [Radix Colors] Collection: purpleDark */
  val purpleDark =
      listOf(
          Color.hsl(284f, 0.200f, 0.096f),
          Color.hsl(283f, 0.300f, 0.118f),
          Color.hsl(281f, 0.375f, 0.165f),
          Color.hsl(280f, 0.412f, 0.200f),
          Color.hsl(279f, 0.438f, 0.233f),
          Color.hsl(277f, 0.464f, 0.275f),
          Color.hsl(275f, 0.493f, 0.346f),
          Color.hsl(272f, 0.521f, 0.459f),
          Color.hsl(272f, 0.510f, 0.540f),
          Color.hsl(273f, 0.573f, 0.591f),
          Color.hsl(275f, 0.800f, 0.710f),
          Color.hsl(279f, 0.750f, 0.957f),
      )
  /** [Radix Colors] Collection: purpleDarkA */
  val purpleDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(280f, 0.965f, 0.575f, 0.045f),
          Color.hsl(279f, 0.987f, 0.628f, 0.129f),
          Color.hsl(279f, 0.991f, 0.640f, 0.191f),
          Color.hsl(278f, 0.998f, 0.642f, 0.248f),
          Color.hsl(276f, 0.996f, 0.646f, 0.328f),
          Color.hsl(274f, 0.999f, 0.646f, 0.456f),
          Color.hsl(272f, 0.997f, 0.646f, 0.660f),
          Color.hsl(272f, 0.999f, 0.691f, 0.748f),
          Color.hsl(273f, 1.000f, 0.713f, 0.801f),
          Color.hsl(275f, 0.999f, 0.753f, 0.934f),
          Color.hsl(286f, 1.000f, 0.971f, 0.980f),
      )
  /** [Radix Colors] Collection: red */
  val red =
      listOf(
          Color.hsl(359f, 1.000f, 0.994f),
          Color.hsl(359f, 1.000f, 0.986f),
          Color.hsl(360f, 1.000f, 0.968f),
          Color.hsl(360f, 0.979f, 0.948f),
          Color.hsl(360f, 0.902f, 0.919f),
          Color.hsl(360f, 0.817f, 0.878f),
          Color.hsl(359f, 0.742f, 0.817f),
          Color.hsl(359f, 0.695f, 0.743f),
          Color.hsl(358f, 0.750f, 0.590f),
          Color.hsl(358f, 0.694f, 0.552f),
          Color.hsl(358f, 0.650f, 0.487f),
          Color.hsl(354f, 0.500f, 0.146f),
      )
  /** [Radix Colors] Collection: redA */
  val redA =
      listOf(
          Color.hsl(0f, 1.000f, 0.510f, 0.012f),
          Color.hsl(0f, 1.000f, 0.510f, 0.032f),
          Color.hsl(0f, 1.000f, 0.502f, 0.063f),
          Color.hsl(0f, 1.000f, 0.500f, 0.102f),
          Color.hsl(0f, 0.999f, 0.475f, 0.153f),
          Color.hsl(0f, 0.995f, 0.449f, 0.224f),
          Color.hsl(359f, 0.997f, 0.427f, 0.318f),
          Color.hsl(359f, 0.996f, 0.411f, 0.436f),
          Color.hsl(358f, 0.999f, 0.429f, 0.718f),
          Color.hsl(358f, 0.999f, 0.410f, 0.761f),
          Color.hsl(358f, 0.998f, 0.383f, 0.832f),
          Color.hsl(355f, 0.993f, 0.079f, 0.926f),
      )
  /** [Radix Colors] Collection: redDark */
  val redDark =
      listOf(
          Color.hsl(353f, 0.230f, 0.098f),
          Color.hsl(357f, 0.344f, 0.120f),
          Color.hsl(356f, 0.434f, 0.164f),
          Color.hsl(356f, 0.476f, 0.192f),
          Color.hsl(356f, 0.511f, 0.219f),
          Color.hsl(356f, 0.552f, 0.259f),
          Color.hsl(357f, 0.602f, 0.318f),
          Color.hsl(358f, 0.650f, 0.404f),
          Color.hsl(358f, 0.750f, 0.590f),
          Color.hsl(358f, 0.853f, 0.640f),
          Color.hsl(358f, 1.000f, 0.695f),
          Color.hsl(351f, 0.890f, 0.960f),
      )
  /** [Radix Colors] Collection: redDarkA */
  val redDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(5f, 0.985f, 0.538f, 0.045f),
          Color.hsl(359f, 0.991f, 0.611f, 0.130f),
          Color.hsl(358f, 0.988f, 0.610f, 0.184f),
          Color.hsl(357f, 0.996f, 0.603f, 0.237f),
          Color.hsl(358f, 0.996f, 0.603f, 0.322f),
          Color.hsl(357f, 1.000f, 0.595f, 0.442f),
          Color.hsl(358f, 0.998f, 0.591f, 0.621f),
          Color.hsl(358f, 1.000f, 0.655f, 0.884f),
          Color.hsl(358f, 1.000f, 0.675f, 0.942f),
          Color.hsl(358f, 1.000f, 0.697f, 0.980f),
          Color.hsl(352f, 1.000f, 0.971f, 0.980f),
      )
  /** [Radix Colors] Collection: sage */
  val sage =
      listOf(
          Color.hsl(155f, 0.300f, 0.988f),
          Color.hsl(150f, 0.167f, 0.976f),
          Color.hsl(151f, 0.106f, 0.952f),
          Color.hsl(151f, 0.088f, 0.930f),
          Color.hsl(151f, 0.078f, 0.908f),
          Color.hsl(152f, 0.072f, 0.884f),
          Color.hsl(153f, 0.067f, 0.853f),
          Color.hsl(154f, 0.061f, 0.775f),
          Color.hsl(155f, 0.035f, 0.555f),
          Color.hsl(154f, 0.028f, 0.517f),
          Color.hsl(155f, 0.030f, 0.430f),
          Color.hsl(155f, 0.240f, 0.090f),
      )
  /** [Radix Colors] Collection: sageA */
  val sageA =
      listOf(
          Color.hsl(150f, 0.926f, 0.265f, 0.016f),
          Color.hsl(150f, 0.877f, 0.160f, 0.028f),
          Color.hsl(160f, 0.984f, 0.109f, 0.055f),
          Color.hsl(140f, 0.923f, 0.085f, 0.075f),
          Color.hsl(160f, 0.860f, 0.069f, 0.099f),
          Color.hsl(156f, 0.951f, 0.082f, 0.126f),
          Color.hsl(156f, 0.986f, 0.063f, 0.157f),
          Color.hsl(154f, 0.946f, 0.060f, 0.240f),
          Color.hsl(154f, 0.987f, 0.030f, 0.459f),
          Color.hsl(154f, 0.935f, 0.029f, 0.499f),
          Color.hsl(154f, 0.952f, 0.025f, 0.585f),
          Color.hsl(158f, 0.970f, 0.024f, 0.934f),
      )
  /** [Radix Colors] Collection: sageDark */
  val sageDark =
      listOf(
          Color.hsl(155f, 0.070f, 0.084f),
          Color.hsl(150f, 0.074f, 0.106f),
          Color.hsl(150f, 0.067f, 0.131f),
          Color.hsl(150f, 0.064f, 0.153f),
          Color.hsl(150f, 0.061f, 0.174f),
          Color.hsl(150f, 0.058f, 0.199f),
          Color.hsl(150f, 0.055f, 0.236f),
          Color.hsl(150f, 0.051f, 0.306f),
          Color.hsl(155f, 0.060f, 0.425f),
          Color.hsl(153f, 0.048f, 0.482f),
          Color.hsl(155f, 0.050f, 0.618f),
          Color.hsl(155f, 0.060f, 0.930f),
      )
  /** [Radix Colors] Collection: sageDarkA */
  val sageDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(123f, 0.944f, 0.914f, 0.026f),
          Color.hsl(123f, 0.829f, 0.910f, 0.057f),
          Color.hsl(124f, 0.979f, 0.945f, 0.082f),
          Color.hsl(125f, 0.900f, 0.952f, 0.104f),
          Color.hsl(142f, 0.951f, 0.948f, 0.134f),
          Color.hsl(143f, 0.928f, 0.957f, 0.173f),
          Color.hsl(146f, 0.947f, 0.953f, 0.255f),
          Color.hsl(151f, 0.982f, 0.944f, 0.397f),
          Color.hsl(148f, 0.995f, 0.955f, 0.457f),
          Color.hsl(152f, 0.951f, 0.973f, 0.600f),
          Color.hsl(149f, 0.933f, 0.996f, 0.927f),
      )
  /** [Radix Colors] Collection: sand */
  val sand =
      listOf(
          Color.hsl(50f, 0.200f, 0.990f),
          Color.hsl(60f, 0.077f, 0.975f),
          Color.hsl(59f, 0.065f, 0.951f),
          Color.hsl(58f, 0.061f, 0.929f),
          Color.hsl(57f, 0.060f, 0.907f),
          Color.hsl(56f, 0.059f, 0.884f),
          Color.hsl(55f, 0.059f, 0.852f),
          Color.hsl(51f, 0.060f, 0.771f),
          Color.hsl(50f, 0.020f, 0.557f),
          Color.hsl(55f, 0.017f, 0.519f),
          Color.hsl(50f, 0.020f, 0.431f),
          Color.hsl(50f, 0.060f, 0.100f),
      )
  /** [Radix Colors] Collection: sandA */
  val sandA =
      listOf(
          Color.hsl(60f, 0.893f, 0.183f, 0.012f),
          Color.hsl(60f, 0.781f, 0.090f, 0.028f),
          Color.hsl(60f, 0.990f, 0.039f, 0.051f),
          Color.hsl(60f, 0.889f, 0.059f, 0.075f),
          Color.hsl(60f, 0.860f, 0.069f, 0.099f),
          Color.hsl(60f, 0.932f, 0.052f, 0.122f),
          Color.hsl(60f, 0.983f, 0.051f, 0.157f),
          Color.hsl(51f, 0.941f, 0.060f, 0.244f),
          Color.hsl(60f, 0.998f, 0.017f, 0.451f),
          Color.hsl(60f, 0.907f, 0.018f, 0.491f),
          Color.hsl(45f, 0.937f, 0.015f, 0.577f),
          Color.hsl(60f, 0.980f, 0.007f, 0.906f),
      )
  /** [Radix Colors] Collection: sandDark */
  val sandDark =
      listOf(
          Color.hsl(61f, 0.020f, 0.083f),
          Color.hsl(60f, 0.037f, 0.106f),
          Color.hsl(58f, 0.037f, 0.131f),
          Color.hsl(57f, 0.036f, 0.153f),
          Color.hsl(56f, 0.037f, 0.174f),
          Color.hsl(55f, 0.037f, 0.199f),
          Color.hsl(53f, 0.037f, 0.236f),
          Color.hsl(50f, 0.038f, 0.306f),
          Color.hsl(50f, 0.040f, 0.427f),
          Color.hsl(52f, 0.031f, 0.483f),
          Color.hsl(50f, 0.040f, 0.618f),
          Color.hsl(56f, 0.040f, 0.928f),
      )
  /** [Radix Colors] Collection: sandDarkA */
  val sandDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(60f, 0.898f, 0.914f, 0.026f),
          Color.hsl(60f, 0.955f, 0.925f, 0.056f),
          Color.hsl(60f, 0.756f, 0.964f, 0.078f),
          Color.hsl(60f, 0.819f, 0.952f, 0.104f),
          Color.hsl(41f, 0.876f, 0.948f, 0.134f),
          Color.hsl(60f, 0.954f, 0.962f, 0.172f),
          Color.hsl(49f, 0.935f, 0.957f, 0.254f),
          Color.hsl(52f, 0.973f, 0.962f, 0.391f),
          Color.hsl(52f, 0.978f, 0.967f, 0.451f),
          Color.hsl(51f, 0.970f, 0.978f, 0.597f),
          Color.hsl(60f, 0.887f, 0.998f, 0.923f),
      )
  /** [Radix Colors] Collection: sky */
  val sky =
      listOf(
          Color.hsl(193f, 1.000f, 0.988f),
          Color.hsl(193f, 1.000f, 0.973f),
          Color.hsl(193f, 0.990f, 0.947f),
          Color.hsl(193f, 0.914f, 0.914f),
          Color.hsl(194f, 0.820f, 0.866f),
          Color.hsl(194f, 0.741f, 0.795f),
          Color.hsl(194f, 0.723f, 0.696f),
          Color.hsl(193f, 0.779f, 0.539f),
          Color.hsl(193f, 0.980f, 0.700f),
          Color.hsl(193f, 0.870f, 0.665f),
          Color.hsl(195f, 1.000f, 0.315f),
          Color.hsl(195f, 1.000f, 0.130f),
      )
  /** [Radix Colors] Collection: skyA */
  val skyA =
      listOf(
          Color.hsl(190f, 1.000f, 0.510f, 0.024f),
          Color.hsl(193f, 1.000f, 0.501f, 0.055f),
          Color.hsl(193f, 1.000f, 0.501f, 0.106f),
          Color.hsl(194f, 0.996f, 0.477f, 0.165f),
          Color.hsl(194f, 0.992f, 0.454f, 0.244f),
          Color.hsl(194f, 0.999f, 0.423f, 0.357f),
          Color.hsl(194f, 0.998f, 0.422f, 0.526f),
          Color.hsl(193f, 0.999f, 0.438f, 0.820f),
          Color.hsl(193f, 0.997f, 0.494f, 0.593f),
          Color.hsl(193f, 0.998f, 0.466f, 0.628f),
          Color.hsl(196f, 1.000f, 0.312f, 0.980f),
          Color.hsl(196f, 1.000f, 0.122f, 0.980f),
      )
  /** [Radix Colors] Collection: skyDark */
  val skyDark =
      listOf(
          Color.hsl(205f, 0.450f, 0.086f),
          Color.hsl(202f, 0.714f, 0.096f),
          Color.hsl(201f, 0.746f, 0.122f),
          Color.hsl(201f, 0.774f, 0.144f),
          Color.hsl(200f, 0.803f, 0.165f),
          Color.hsl(200f, 0.841f, 0.189f),
          Color.hsl(199f, 0.902f, 0.221f),
          Color.hsl(198f, 1.000f, 0.261f),
          Color.hsl(193f, 0.980f, 0.700f),
          Color.hsl(192f, 1.000f, 0.770f),
          Color.hsl(192f, 0.850f, 0.558f),
          Color.hsl(198f, 0.980f, 0.958f),
      )
  /** [Radix Colors] Collection: skyDarkA */
  val skyDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(208f, 1.000f, 0.498f, 0.045f),
          Color.hsl(201f, 1.000f, 0.498f, 0.099f),
          Color.hsl(201f, 1.000f, 0.500f, 0.148f),
          Color.hsl(200f, 1.000f, 0.498f, 0.198f),
          Color.hsl(199f, 1.000f, 0.499f, 0.256f),
          Color.hsl(199f, 1.000f, 0.499f, 0.337f),
          Color.hsl(199f, 1.000f, 0.500f, 0.453f),
          Color.hsl(192f, 1.000f, 0.708f, 0.980f),
          Color.hsl(190f, 1.000f, 0.776f, 0.980f),
          Color.hsl(192f, 0.999f, 0.596f, 0.924f),
          Color.hsl(189f, 1.000f, 0.968f, 0.980f),
      )
  /** [Radix Colors] Collection: slate */
  val slate =
      listOf(
          Color.hsl(206f, 0.300f, 0.988f),
          Color.hsl(210f, 0.167f, 0.976f),
          Color.hsl(209f, 0.133f, 0.953f),
          Color.hsl(209f, 0.122f, 0.932f),
          Color.hsl(208f, 0.117f, 0.911f),
          Color.hsl(208f, 0.113f, 0.889f),
          Color.hsl(207f, 0.111f, 0.859f),
          Color.hsl(205f, 0.107f, 0.780f),
          Color.hsl(206f, 0.060f, 0.561f),
          Color.hsl(206f, 0.058f, 0.523f),
          Color.hsl(206f, 0.060f, 0.435f),
          Color.hsl(206f, 0.240f, 0.090f),
      )
  /** [Radix Colors] Collection: slateA */
  val slateA =
      listOf(
          Color.hsl(210f, 0.926f, 0.265f, 0.016f),
          Color.hsl(210f, 0.877f, 0.160f, 0.028f),
          Color.hsl(210f, 0.988f, 0.144f, 0.055f),
          Color.hsl(210f, 0.941f, 0.111f, 0.075f),
          Color.hsl(216f, 0.911f, 0.109f, 0.099f),
          Color.hsl(206f, 0.964f, 0.113f, 0.126f),
          Color.hsl(210f, 0.991f, 0.101f, 0.157f),
          Color.hsl(205f, 0.965f, 0.100f, 0.244f),
          Color.hsl(206f, 0.988f, 0.059f, 0.467f),
          Color.hsl(206f, 0.996f, 0.054f, 0.506f),
          Color.hsl(206f, 0.970f, 0.048f, 0.593f),
          Color.hsl(202f, 0.970f, 0.024f, 0.934f),
      )
  /** [Radix Colors] Collection: slateDark */
  val slateDark =
      listOf(
          Color.hsl(200f, 0.070f, 0.088f),
          Color.hsl(195f, 0.071f, 0.110f),
          Color.hsl(197f, 0.068f, 0.136f),
          Color.hsl(198f, 0.066f, 0.158f),
          Color.hsl(199f, 0.064f, 0.179f),
          Color.hsl(201f, 0.062f, 0.205f),
          Color.hsl(203f, 0.060f, 0.243f),
          Color.hsl(207f, 0.056f, 0.316f),
          Color.hsl(206f, 0.060f, 0.439f),
          Color.hsl(206f, 0.052f, 0.495f),
          Color.hsl(206f, 0.060f, 0.630f),
          Color.hsl(210f, 0.060f, 0.930f),
      )
  /** [Radix Colors] Collection: slateDarkA */
  val slateDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(181f, 0.989f, 0.918f, 0.026f),
          Color.hsl(182f, 0.867f, 0.914f, 0.057f),
          Color.hsl(209f, 0.867f, 0.939f, 0.083f),
          Color.hsl(200f, 0.903f, 0.934f, 0.109f),
          Color.hsl(209f, 0.953f, 0.935f, 0.139f),
          Color.hsl(204f, 0.985f, 0.939f, 0.182f),
          Color.hsl(209f, 0.940f, 0.947f, 0.265f),
          Color.hsl(207f, 0.973f, 0.940f, 0.412f),
          Color.hsl(209f, 0.994f, 0.952f, 0.472f),
          Color.hsl(208f, 0.987f, 0.968f, 0.615f),
          Color.hsl(211f, 0.867f, 0.996f, 0.927f),
      )
  /** [Radix Colors] Collection: teal */
  val teal =
      listOf(
          Color.hsl(165f, 0.600f, 0.988f),
          Color.hsl(169f, 0.647f, 0.967f),
          Color.hsl(169f, 0.598f, 0.940f),
          Color.hsl(169f, 0.531f, 0.902f),
          Color.hsl(170f, 0.471f, 0.850f),
          Color.hsl(170f, 0.426f, 0.779f),
          Color.hsl(170f, 0.399f, 0.681f),
          Color.hsl(172f, 0.421f, 0.525f),
          Color.hsl(173f, 0.800f, 0.360f),
          Color.hsl(173f, 0.834f, 0.325f),
          Color.hsl(174f, 0.900f, 0.252f),
          Color.hsl(170f, 0.500f, 0.125f),
      )
  /** [Radix Colors] Collection: tealA */
  val tealA =
      listOf(
          Color.hsl(165f, 0.952f, 0.412f, 0.020f),
          Color.hsl(169f, 0.995f, 0.394f, 0.055f),
          Color.hsl(167f, 0.976f, 0.381f, 0.095f),
          Color.hsl(168f, 0.981f, 0.346f, 0.150f),
          Color.hsl(170f, 0.994f, 0.323f, 0.220f),
          Color.hsl(170f, 0.997f, 0.301f, 0.314f),
          Color.hsl(170f, 0.993f, 0.287f, 0.448f),
          Color.hsl(172f, 0.998f, 0.297f, 0.675f),
          Color.hsl(173f, 0.998f, 0.311f, 0.930f),
          Color.hsl(173f, 0.997f, 0.287f, 0.946f),
          Color.hsl(174f, 0.998f, 0.233f, 0.977f),
          Color.hsl(171f, 0.988f, 0.068f, 0.938f),
      )
  /** [Radix Colors] Collection: tealDark */
  val tealDark =
      listOf(
          Color.hsl(168f, 0.480f, 0.065f),
          Color.hsl(169f, 0.778f, 0.071f),
          Color.hsl(170f, 0.761f, 0.092f),
          Color.hsl(171f, 0.758f, 0.110f),
          Color.hsl(171f, 0.757f, 0.128f),
          Color.hsl(172f, 0.758f, 0.151f),
          Color.hsl(172f, 0.767f, 0.186f),
          Color.hsl(173f, 0.802f, 0.237f),
          Color.hsl(173f, 0.800f, 0.360f),
          Color.hsl(174f, 0.839f, 0.382f),
          Color.hsl(174f, 0.900f, 0.407f),
          Color.hsl(166f, 0.730f, 0.931f),
      )
  /** [Radix Colors] Collection: tealDarkA */
  val tealDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(171f, 1.000f, 0.492f, 0.031f),
          Color.hsl(172f, 1.000f, 0.497f, 0.070f),
          Color.hsl(175f, 1.000f, 0.497f, 0.105f),
          Color.hsl(174f, 0.989f, 0.501f, 0.140f),
          Color.hsl(174f, 1.000f, 0.518f, 0.187f),
          Color.hsl(173f, 0.996f, 0.532f, 0.257f),
          Color.hsl(174f, 0.996f, 0.533f, 0.366f),
          Color.hsl(173f, 0.999f, 0.546f, 0.609f),
          Color.hsl(174f, 0.999f, 0.538f, 0.670f),
          Color.hsl(174f, 1.000f, 0.520f, 0.748f),
          Color.hsl(166f, 0.986f, 0.950f, 0.979f),
      )
  /** [Radix Colors] Collection: tomato */
  val tomato =
      listOf(
          Color.hsl(10f, 1.000f, 0.994f),
          Color.hsl(8f, 1.000f, 0.984f),
          Color.hsl(8f, 1.000f, 0.966f),
          Color.hsl(8f, 1.000f, 0.943f),
          Color.hsl(8f, 0.928f, 0.910f),
          Color.hsl(9f, 0.847f, 0.863f),
          Color.hsl(10f, 0.773f, 0.795f),
          Color.hsl(10f, 0.716f, 0.710f),
          Color.hsl(10f, 0.780f, 0.540f),
          Color.hsl(10f, 0.715f, 0.500f),
          Color.hsl(10f, 0.820f, 0.435f),
          Color.hsl(10f, 0.500f, 0.135f),
      )
  /** [Radix Colors] Collection: tomatoA */
  val tomatoA =
      listOf(
          Color.hsl(0f, 1.000f, 0.510f, 0.012f),
          Color.hsl(8f, 1.000f, 0.510f, 0.032f),
          Color.hsl(7f, 1.000f, 0.502f, 0.067f),
          Color.hsl(8f, 1.000f, 0.501f, 0.114f),
          Color.hsl(7f, 0.995f, 0.479f, 0.173f),
          Color.hsl(9f, 0.999f, 0.462f, 0.255f),
          Color.hsl(10f, 0.998f, 0.436f, 0.365f),
          Color.hsl(10f, 0.995f, 0.418f, 0.499f),
          Color.hsl(10f, 0.999f, 0.438f, 0.820f),
          Color.hsl(10f, 1.000f, 0.418f, 0.859f),
          Color.hsl(10f, 0.999f, 0.388f, 0.922f),
          Color.hsl(10f, 0.990f, 0.074f, 0.934f),
      )
  /** [Radix Colors] Collection: tomatoDark */
  val tomatoDark =
      listOf(
          Color.hsl(10f, 0.230f, 0.094f),
          Color.hsl(9f, 0.448f, 0.114f),
          Color.hsl(8f, 0.520f, 0.153f),
          Color.hsl(7f, 0.563f, 0.180f),
          Color.hsl(7f, 0.601f, 0.206f),
          Color.hsl(8f, 0.648f, 0.240f),
          Color.hsl(8f, 0.712f, 0.291f),
          Color.hsl(10f, 0.802f, 0.357f),
          Color.hsl(10f, 0.780f, 0.540f),
          Color.hsl(10f, 0.817f, 0.590f),
          Color.hsl(10f, 0.850f, 0.628f),
          Color.hsl(10f, 0.890f, 0.960f),
      )
  /** [Radix Colors] Collection: tomatoDarkA */
  val tomatoDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(5f, 1.000f, 0.496f, 0.058f),
          Color.hsl(6f, 0.996f, 0.549f, 0.133f),
          Color.hsl(6f, 0.992f, 0.554f, 0.191f),
          Color.hsl(6f, 0.995f, 0.558f, 0.244f),
          Color.hsl(7f, 0.997f, 0.559f, 0.319f),
          Color.hsl(8f, 0.998f, 0.548f, 0.434f),
          Color.hsl(10f, 0.998f, 0.535f, 0.598f),
          Color.hsl(10f, 1.000f, 0.597f, 0.885f),
          Color.hsl(10f, 1.000f, 0.636f, 0.916f),
          Color.hsl(10f, 0.997f, 0.664f, 0.939f),
          Color.hsl(12f, 1.000f, 0.971f, 0.980f),
      )
  /** [Radix Colors] Collection: violet */
  val violet =
      listOf(
          Color.hsl(255f, 0.650f, 0.994f),
          Color.hsl(252f, 1.000f, 0.990f),
          Color.hsl(252f, 0.969f, 0.974f),
          Color.hsl(252f, 0.915f, 0.955f),
          Color.hsl(252f, 0.851f, 0.930f),
          Color.hsl(252f, 0.778f, 0.894f),
          Color.hsl(252f, 0.710f, 0.837f),
          Color.hsl(252f, 0.686f, 0.763f),
          Color.hsl(252f, 0.560f, 0.575f),
          Color.hsl(251f, 0.481f, 0.535f),
          Color.hsl(250f, 0.430f, 0.480f),
          Color.hsl(254f, 0.600f, 0.185f),
      )
  /** [Radix Colors] Collection: violetA */
  val violetA =
      listOf(
          Color.hsl(270f, 0.943f, 0.346f, 0.012f),
          Color.hsl(252f, 1.000f, 0.510f, 0.020f),
          Color.hsl(254f, 1.000f, 0.500f, 0.051f),
          Color.hsl(251f, 0.983f, 0.482f, 0.087f),
          Color.hsl(252f, 0.990f, 0.457f, 0.130f),
          Color.hsl(251f, 0.991f, 0.440f, 0.189f),
          Color.hsl(252f, 0.995f, 0.417f, 0.279f),
          Color.hsl(252f, 1.000f, 0.407f, 0.400f),
          Color.hsl(252f, 0.999f, 0.358f, 0.663f),
          Color.hsl(251f, 0.996f, 0.325f, 0.691f),
          Color.hsl(250f, 0.998f, 0.284f, 0.726f),
          Color.hsl(254f, 0.995f, 0.119f, 0.926f),
      )
  /** [Radix Colors] Collection: violetDark */
  val violetDark =
      listOf(
          Color.hsl(250f, 0.200f, 0.102f),
          Color.hsl(255f, 0.303f, 0.129f),
          Color.hsl(253f, 0.370f, 0.184f),
          Color.hsl(252f, 0.401f, 0.225f),
          Color.hsl(252f, 0.422f, 0.262f),
          Color.hsl(251f, 0.443f, 0.311f),
          Color.hsl(250f, 0.468f, 0.389f),
          Color.hsl(250f, 0.518f, 0.512f),
          Color.hsl(252f, 0.560f, 0.575f),
          Color.hsl(251f, 0.632f, 0.632f),
          Color.hsl(250f, 0.950f, 0.768f),
          Color.hsl(252f, 0.870f, 0.964f),
      )
  /** [Radix Colors] Collection: violetDarkA */
  val violetDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(258f, 0.982f, 0.610f, 0.054f),
          Color.hsl(252f, 0.988f, 0.658f, 0.148f),
          Color.hsl(253f, 0.997f, 0.657f, 0.219f),
          Color.hsl(252f, 0.997f, 0.664f, 0.286f),
          Color.hsl(251f, 0.997f, 0.662f, 0.371f),
          Color.hsl(250f, 0.997f, 0.663f, 0.514f),
          Color.hsl(250f, 0.997f, 0.661f, 0.733f),
          Color.hsl(252f, 0.999f, 0.703f, 0.786f),
          Color.hsl(251f, 0.999f, 0.729f, 0.844f),
          Color.hsl(250f, 1.000f, 0.779f, 0.980f),
          Color.hsl(254f, 1.000f, 0.975f, 0.980f),
      )
  /** [Radix Colors] Collection: whiteA */
  val whiteA =
      listOf(
          Color.hsl(0f, 0.000f, 1.000f, 0.000f),
          Color.hsl(0f, 0.000f, 1.000f, 0.013f),
          Color.hsl(0f, 0.000f, 1.000f, 0.034f),
          Color.hsl(0f, 0.000f, 1.000f, 0.056f),
          Color.hsl(0f, 0.000f, 1.000f, 0.086f),
          Color.hsl(0f, 0.000f, 1.000f, 0.124f),
          Color.hsl(0f, 0.000f, 1.000f, 0.176f),
          Color.hsl(0f, 0.000f, 1.000f, 0.249f),
          Color.hsl(0f, 0.000f, 1.000f, 0.386f),
          Color.hsl(0f, 0.000f, 1.000f, 0.446f),
          Color.hsl(0f, 0.000f, 1.000f, 0.592f),
          Color.hsl(0f, 0.000f, 1.000f, 0.923f),
      )
  /** [Radix Colors] Collection: yellow */
  val yellow =
      listOf(
          Color.hsl(60f, 0.540f, 0.985f),
          Color.hsl(52f, 1.000f, 0.955f),
          Color.hsl(55f, 1.000f, 0.909f),
          Color.hsl(54f, 1.000f, 0.866f),
          Color.hsl(52f, 0.979f, 0.820f),
          Color.hsl(50f, 0.894f, 0.761f),
          Color.hsl(47f, 0.804f, 0.680f),
          Color.hsl(48f, 1.000f, 0.461f),
          Color.hsl(53f, 0.920f, 0.500f),
          Color.hsl(50f, 1.000f, 0.485f),
          Color.hsl(42f, 1.000f, 0.290f),
          Color.hsl(40f, 0.550f, 0.135f),
      )
  /** [Radix Colors] Collection: yellowA */
  val yellowA =
      listOf(
          Color.hsl(60f, 0.943f, 0.346f, 0.024f),
          Color.hsl(52f, 1.000f, 0.504f, 0.091f),
          Color.hsl(55f, 1.000f, 0.502f, 0.181f),
          Color.hsl(54f, 1.000f, 0.501f, 0.267f),
          Color.hsl(52f, 0.999f, 0.495f, 0.357f),
          Color.hsl(50f, 1.000f, 0.474f, 0.451f),
          Color.hsl(47f, 0.998f, 0.446f, 0.577f),
          Color.hsl(48f, 1.000f, 0.460f, 0.980f),
          Color.hsl(53f, 1.000f, 0.480f, 0.961f),
          Color.hsl(50f, 1.000f, 0.484f, 0.980f),
          Color.hsl(42f, 1.000f, 0.286f, 0.980f),
          Color.hsl(41f, 0.989f, 0.080f, 0.942f),
      )
  /** [Radix Colors] Collection: yellowDark */
  val yellowDark =
      listOf(
          Color.hsl(45f, 1.000f, 0.055f),
          Color.hsl(46f, 1.000f, 0.067f),
          Color.hsl(45f, 1.000f, 0.087f),
          Color.hsl(45f, 1.000f, 0.104f),
          Color.hsl(47f, 1.000f, 0.121f),
          Color.hsl(49f, 1.000f, 0.143f),
          Color.hsl(49f, 0.903f, 0.184f),
          Color.hsl(50f, 1.000f, 0.220f),
          Color.hsl(53f, 0.920f, 0.500f),
          Color.hsl(54f, 1.000f, 0.680f),
          Color.hsl(48f, 1.000f, 0.470f),
          Color.hsl(53f, 1.000f, 0.910f),
      )
  /** [Radix Colors] Collection: yellowDarkA */
  val yellowDarkA =
      listOf(
          Color.hsl(0f, 0.000f, 0.000f, 0.000f),
          Color.hsl(49f, 1.000f, 0.491f, 0.027f),
          Color.hsl(45f, 1.000f, 0.497f, 0.071f),
          Color.hsl(46f, 1.000f, 0.497f, 0.111f),
          Color.hsl(47f, 1.000f, 0.499f, 0.150f),
          Color.hsl(51f, 1.000f, 0.498f, 0.199f),
          Color.hsl(51f, 0.998f, 0.536f, 0.269f),
          Color.hsl(51f, 1.000f, 0.499f, 0.371f),
          Color.hsl(53f, 1.000f, 0.520f, 0.956f),
          Color.hsl(56f, 1.000f, 0.684f, 0.980f),
          Color.hsl(48f, 1.000f, 0.500f, 0.934f),
          Color.hsl(60f, 1.000f, 0.918f, 0.980f),
      )
}
